### ISSUE TITLE
RPC errors when connected to Arbitrum Rinkeby testnet

### ISSUE THREAD

**Issue by luzzif** [DXgovernance/dxvote#100]
**Describe the bug**
RPC errors when connected to Arbitrum Rinkeby testnet.

**To Reproduce**
1. Go to DXvote
2. Connect to Arbitrum testnet
3. See error in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/12766550/131671264-e0444b6f-77ef-48f2-bae7-85d1c48734a2.png)

**Comment by AugustoL** [comment]
Fixed by catching the errors in the BlockchainFecth and Cache, still supeeer slow to load.
