### ISSUE TITLE
Show the exact number of REP in DXvote alongside all %ages

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#101]
**Is your feature request related to a problem? Please describe.**
Yes, need to see exact number of REP.

**Describe the solution you'd like**
Show the exact number of REP in DXvote alongside all %ages

**Comment by skyminelabs** [comment]
Faster than Powers!

**Comment by luchux** [comment]
@rossneilson is this repeated in new REP % component issue?

**Comment by rossneilson** [comment]
I think it could be a neat feature in that issue where on hover it shows the exact number
