### ISSUE TITLE
Proposal shows "Pending Execution" when it's really "Expired in Queue"

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#119]
**Describe the bug**
Proposal shows "Pending Execution" when it's really "Expired in Queue"

**To Reproduce**
1. Go to a proposal that is "Pending Execution" but has already passed the time that you have to execute.  
2. You will see the button to "Execute"
3. But when you do, you will learn "

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/57817726/132284834-efa1a78f-7a42-4b41-aee9-74cfb64abb33.png)

![image](https://user-images.githubusercontent.com/57817726/132285083-d6ce013a-ea75-4ca9-b499-c2e7c52d9f25.png)

**Comment by AugustoL** [comment]
This happened because the positive votes where less to the required in % for boosted proposals, it was expected to fail.
