### ISSUE TITLE
Proposal showing "Redeem" button even after redeeming the Staking token

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#120]
**Describe the bug**
Proposal showing "Redeem" button even after redeeming the Staking token

**To Reproduce**
1. Go to: https://augustol.github.io/dxvote/#/rinkeby/proposal/0x379308ac391ff9c7fa3fe834ea24bd2cb0f1686a378c18586cf90cae8db2a6ca
2. I see "Redeem" button.  
3. Even after redeeming three times, i still see Redeem button

**Expected behavior**
Button should go away.  

Can i redeem the bounty reward too?

**Screenshots**
![image](https://user-images.githubusercontent.com/57817726/132285505-f1459543-a6d6-44fc-ad24-44edfd8e37d8.png)

**Comment by AugustoL** [comment]
@skyminert can you confirmed if this is fixed?

**Comment by skyminelabs** [comment]
I still see the "Redeem" button there.  

And just did another Redeem txn:
https://rinkeby.etherscan.io/tx/0x69697f57984f85b903b74b8e21483b13098f46b4e2490600e7ce1d478e18b808

![image](https://user-images.githubusercontent.com/57817726/132606476-62acc76d-4f67-44f7-a57b-82542bfa9260.png)

What is different about this one?
