### ISSUE TITLE
Request for Dark Mode...please

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#122]
**Describe the solution you'd like**
Request for Dark Mode...please

**Describe alternatives you've considered**
Considered using another governance system that has dark mode.  

**Additional context**
Please

**Comment by adamazad** [comment]
It's in progress.

**Comment by AugustoL** [comment]
closed in favor of #87 when it is ready you will be the first one to try it @skyminert , we will give you early access to it
