### ISSUE TITLE
Add Redeemer contract

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#129]
We are making individual redeems in the dapp while we can be using the Redeemer contract used in alchemy.

https://github.com/DXgovernance/dxdao-contracts/blob/main/contracts/daostack/utils/Redeemer.sol

We should add the Redeemer contract into the source code, the ABI from the dxdao-contracts repo like we do with the other smart contracts and the address from the config file, it would be just addingthe address to the utils section.

Lets create a redeemAll function in the service/daoService file and use it in the pages/proposal component.

With this addition we will be doing redeems of everything in one tx.

**Comment by hhamud** [comment]
The redeemer abi from dxdao-contracts is already in the repo with addresses pointing to the deployed contracts on both mainnet and xdai. Do you mean you want the redeemer abi from daostack/arc instead?. I've taken a look at that contract as well and there is no `redeemAll` function available to execute multiple redeems in a single transaction call.

Some clarifications are needed. @AugustoL
