### ISSUE TITLE
Error creating liquidity mining campaign through guided form on Arbitrum Rinkeby

### ISSUE THREAD

**Issue by luzzif** [DXgovernance/dxvote#134]
**Describe the bug**
When trying to create a liquidity mining campaign on Arbitrum Rinkeby, I get this error: `[PROPOSAL_ERROR] TypeError: t.map is not a function`

**To Reproduce**
1. Go to the proposal creation page
2. Add an approve call for 100 SWPR to the liquidity mining campaigns factory contract (`0x41e657cAdE74f45b7E2F0F4a5AeE0239f2fB4E1F`)
3. Add a liquidity mining campaign creation proposal with the following parameters:
- Reward tokens: `["0x8f2072c2142d9ffdc785955e0ce71561753d44fb"]`
- Stakable token: `0x1a9cbc04eab03da25e98b1c2c638ff71d638c49c`
- Reward amounts: `["100000000000000000000"]`
- Starting timestamp: 1 day from when the proposal is created
- Ending timestamp: anything greater than the starting timestamp
- Timelocked: false
- Cap: 0
4. Try to submit the proposal and see this error in the console:
![image](https://user-images.githubusercontent.com/12766550/132710835-276c4fd7-37a8-4a00-9fdd-9387af17be1c.png)

**Comment by AugustoL** [comment]
@luzzif should be fixed now, if you can confirm please, use the array without quotes, like [address] and no ["address"]

**Comment by AugustoL** [comment]
Fixed, right? @luzzif
