### ISSUE TITLE
UI shows 'false' where it should have the Unix time stamp

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#135]
**Describe the bug**
Liquidity mining campaign proposal and the calls show the right info except for the 'ending at false', this should be the Unix timestamp

https://dxgovernance.github.io/dxvote/#/arbitrumTestnet/proposal/0xa2f706d59c3671119a3b1cfe771a9e954183b122d0ce3938be7faf30adca4592 

![paste (3)](https://user-images.githubusercontent.com/47428627/132714189-8dd89a6c-6a7f-4119-8252-39a33fdbd43f.png)

**Comment by AugustoL** [comment]
@powerschris can you confirm if it was fixed?

**Comment by powerschris** [comment]
Looks to have fixed the cap at the end but not the Unix timestamp. still 'ending at false'

<img width="845" alt="Screen Shot 2021-09-12 at 4 07 11 PM" src="https://user-images.githubusercontent.com/47428627/133001300-f2225a82-bcd4-4495-88af-0881c3b1bcf5.png">

**Comment by rossneilson** [comment]
Fixed in #183
