### ISSUE TITLE
Prevent UI changes upon proposal submission

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#141]
**Describe the bug**
When submitting a proposal changes need to be made to arrays and booleans for them to be converted from strings to their respective types before encoding. However this results in the UI changing causing doubts from users about whether the data was properly encoded. 
This could be fixed by storing the data in a new variable and editing this for encoding so the UI data will remain unchanged. 

**To Reproduce**
1. Go to new proposal page
2. Select swapr liquidity mining campaigns 
3. Fill out inputs including arrays and boolean values
4. See change in UI

**Expected behavior**
Nothing should change and data should be properly encoded

**Comment by luchux** [comment]
I could take this one, but I can't assign myself yet (i guess cause i am not contributor in the repo? )
