### ISSUE TITLE
Default should not show unboosted proposals

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#147]
**Is your feature request related to a problem? Please describe.**
When looking at the proposal view in DXvote, it sorts by relevant proposals, which is mostly based upon when the proposal is finished. This makes sense for boosted proposal but it gets clogged up when there are unboosted (often mistake) proposals that are expiring. As can be seen here.
<img width="1188" alt="Screen Shot 2021-09-14 at 3 39 21 PM" src="https://user-images.githubusercontent.com/47428627/133323064-86b85f30-4b30-43b4-b38a-d8cc18432df4.png">

The Amphiboly proposals are not relevant. Luzzifoss is

**Describe the solution you'd like**
I think the default view should only show 'boosted proposals' or maybe if it has a certain amount of REP voted for it (for the case of majority votes?)

**Comment by AugustoL** [comment]
Hmmm, for security reasons we need to show all proposals by default, what we can do is show proposals with votes higher,d put the ones with no votes in a lower "priority".

**Comment by powerschris** [comment]
Yeah. Think it should just be about the sorting. If a proposal is about to expire with no votes, it's not important. 

The default proposal view is something to think about. I'm not sure what is best. I actually think I like Alchemy's scheme-level layout more than the proposal scroll. Perhaps its just because the UI does a good job of separating important information from each other - the proposal text, tokens/REP being minted, votes for against/stake. All look very distinctive.

**Comment by hhamud** [comment]
Dxvote is overdue a complete UI overhaul. I know @rossneilson and @AugustoL are currently working on a roadmap, so we'll know soon when that will be started.

**Comment by rossneilson** [comment]
> Dxvote is overdue a complete UI overhaul. I know @rossneilson and @AugustoL are currently working on a roadmap, so we'll know soon when that will be started.

Yeah, we actually talked about Chris' proposed changed the other day, but in the meantime altering the sorting could be a quick solution
