### ISSUE TITLE
Make proposal token transfers easy to Read

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#151]
**Is your feature request related to a problem? Please describe.**
It's hard to see the calls that a proposal will make on DXvote. This is most important for the funds transferred and new REP minted. It would be great to have a quick view of the proposal where you can see what's being transferred. 

![Image 9-15-21 at 4 58 PM](https://user-images.githubusercontent.com/47428627/133509124-fc2b9508-7c94-4f5d-a168-aeff823ac5c7.jpg)

**Describe the solution you'd like**
Alchemy does this pretty effective

![Screen Shot 2021-09-15 at 5 01 11 PM](https://user-images.githubusercontent.com/47428627/133509175-d33e26f9-3baa-4b2a-95a6-bd88e04e74b1.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by AugustoL** [comment]
Fixed in latest deployment
