### ISSUE TITLE
Integrate ENS into UI

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#152]
**Is your feature request related to a problem? Please describe.**
Would be great to get CaneyFork.eth showing in the top right instead of the 0x... :)

Maybe some other way to help people recognize that addresses are certain individuals/stakeholders. Alchemy lets you show a name.

**Comment by AugustoL** [comment]
ENS name resolution is integrated in web3, https://web3js.readthedocs.io/en/v1.5.2/web3-eth-ens.html

Also this can be done in the common address component.

And the common address component should be use more in the dapp.

**Comment by rossneilson** [comment]
Haha, I wrote this down on a piece of paper as a feature to add, looks like you beat me to it

**Comment by AugustoL** [comment]
Closed in favor of #162
