### ISSUE TITLE
BlockchainLink Common component refactor

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#162]
**Description**
The BlockchainLink component now receives:
```
text,
size = 'default',
type = 'default',
toCopy = false,
onlyIcon = false,
```
As element attributes used for configuration, maybe we can receive only address as text and a config attribute with therest of the values.

**Proposed Solution**
If the address is an ERC20 token registered in the config show the token symbol instead with links to the token explorer, and the option to copy the token address.
If the address is an ens domain show the ens domain name with a link to the blockchain explorer address and option to copy the address.
If the address is an known dxvote contract (avatar,controller, etc) domain show the contract name with a link to the blockchain explorer address and option to copy the address.

**Expected Behavior**
See this component easy to use with an stadarized way of displaying addresses in the dapp.

**Comment by AugustoL** [comment]
ENS name resolution is integrated in web3, https://web3js.readthedocs.io/en/v1.5.2/web3-eth-ens.html

**Comment by luchux** [comment]
@AugustoL im gonna take  this one
