### ISSUE TITLE
Value common component

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#164]
**Description**
Add a component in the common folder to be used all around the dapp for values.

**Proposed Solution**
The component will receive the value in BN format, the asset name or address (is address is sent detect it by 0x in the first string position), the decimals of the asset and if the value demomination to be used by default is 0 or the asset decimals.

When the user click in the value the displayed amount changes between 0 decimals and max number of decimals (most probably 18).

**Expected Behavior**
Use this component as much as possible in the dapp.

**Comment by luchux** [comment]
@AugustoL  
Can you pinpoint where this component should be used ?  
Wondering if there are use cases of overlap with https://github.com/DXgovernance/dxvote/issues/162 (BlockchainLink)
