### ISSUE TITLE
Toggle for simple/advanced settings

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#174]
**This will be a common UI component used throughout new UX flows**

Currently the button for toggling advanced and simple input for proposal calls is a little complex to understand which state is being used for new users. This is especially confusing as the advanced box (encoded calls) has fewer inputs making it look simple.
<img width="1013" alt="スクリーンショット 2021-09-24 11 55 45" src="https://user-images.githubusercontent.com/39137239/134663565-e60dc104-7feb-49d0-9f49-f19837a26d1a.png">

I think the best solution for this would be a binary switch style component which shows the current state and allows it to be toggled to the other state.

I have used this package before which would be the easy solution
https://www.npmjs.com/package/react-switch

<img width="132" alt="スクリーンショット 2021-09-24 11 54 40" src="https://user-images.githubusercontent.com/39137239/134663415-7deaee87-22a4-4127-ae68-0c1549f2a37a.png">

A custom component would be better for package size, dev can decide if it is worth the effort or not

**Comment by luchux** [comment]
@rossneilson I can take this

**Comment by mprasanjith** [comment]
@rossneilson Do we still need this for the new proposal creation flow?

**Comment by rossneilson** [comment]
Oh completely forgot this was a separate issue. Already added and in my PR, will link it now, thanks

**Comment by rossneilson** [comment]
Although actually I have only made a component and added to new UI, it still needs added to the custom proposal page for advanced options

**Comment by mprasanjith** [comment]
Got it. Will wait until the your PR is merged, and will then update the custom proposal page.
