### ISSUE TITLE
Proposal verification

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#178]
**Problem Description**
Perhaps this is something that @rossneilson is thinking of with the proposal creation UI and ENS names, but I also noticed it because some people use keybase signatures in their proposals for verification, so maybe that could be built in?

just a thought

<img width="819" alt="Screen Shot 2021-09-24 at 12 15 53 PM" src="https://user-images.githubusercontent.com/47428627/134708057-02813012-d3fc-4ca7-82e0-80c48f1e8f8f.png">

although, i kind of prefer going all in on the Ethereum address - that's where the REP is.

**Comment by rossneilson** [comment]
I think saltpack would only work by verifying in keybase, but I dont know a lot about how it works.

There are a few additional things we could do to increase security. One simple option would be showing previous proposals from the person's account to make it clear if they have previously made worker proposals.

The other, which I think is being worked on here #162 ,would make ens names appear and so just encouraging all contributors to have an ens would go a long way I think.

**Comment by powerschris** [comment]
Yes. of course, showing a submitter's REP % is also helpful too.

Just made me think of it!
