### ISSUE TITLE
Proposal sorting

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#179]
**Description**
For the proposal view, imo the default order of proposals as you scroll should be:
Boosted
Pre-boosted
executed succeeded 
In queue 

perhaps, you could switch 'executed succeeded' and 'in queue', but in the current form all of the 'in queue' proposals are before the current boosting proposals.
<img width="417" alt="Screen Shot 2021-09-24 at 12 20 54 PM" src="https://user-images.githubusercontent.com/47428627/134708657-c4431da0-d400-4c8d-ba83-e963aa068ed1.png">
<img width="491" alt="Screen Shot 2021-09-24 at 12 20 43 PM" src="https://user-images.githubusercontent.com/47428627/134708658-8d62821d-9c38-4ada-ab54-56e926ae2369.png">

The current boosting proposals are *VERY IMPORTANT*. A lot of ways the boosting period in holographic consensus could be more important than the voting period (think back to contentious proposals, and it was on the boosting phase). It should be easy to see 'what is boosting' right now. Perhaps that's actually completely separate from the voting experience? Or it's a different user really.

**Comment by hhamud** [comment]
@powerschris checkout the linked Pull Request to see if that solves your problem

**Comment by powerschris** [comment]
That looks great! Sorted boosted, then pre-boosted then in queue
<img width="563" alt="Screen Shot 2021-09-27 at 8 58 40 PM" src="https://user-images.githubusercontent.com/47428627/135005127-dd908572-0e8d-4197-98db-326cd893ce4f.png">
