### ISSUE TITLE
Suggested staking amount needs to be more than, not equal to

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#180]
**Description**
In the boosting phase, DXvote recommends the amount of GEN to stake, but it appears that it is recommending the amount that the stake needs to exceed. I noticed an issue with a proposal from @fluiddrop that was not boosted.

https://dxvote.eth.link/#/xdai/proposal/0x718fe9257b9758c18ca9eef92466119a5c6d6a1e75e225754158895a625eb12a 

He staked 240, but was not boosted. only took a screenshot in proposal view, but it also appeared as 'pre-boosted' on alchemy

<img width="451" alt="Screen Shot 2021-09-24 at 1 00 28 PM" src="https://user-images.githubusercontent.com/47428627/134719743-2dddbd7f-49f3-4825-83c2-2d34826d3d29.png">

<img width="417" alt="Screen Shot 2021-09-24 at 12 20 54 PM" src="https://user-images.githubusercontent.com/47428627/134719771-c471be7d-fb20-44c8-b30a-6bab0a1b87f0.png">

I think it needs to recommend 0.0001 more than what it needs to exceed? 

Like I think this recommendation should actually be 497.8?

<img width="372" alt="Screen Shot 2021-09-24 at 1 58 07 PM" src="https://user-images.githubusercontent.com/47428627/134719981-64fb8127-fead-416e-a024-6c05264b983a.png">

**Comment by powerschris** [comment]
I'm not sure if this issue actually exists. 

I've been using DXvote's recommendations for GEN staking amounts for the last three proposals I've boosted and have not had the same problem. 

We can close this in a few more days assuming no one else recreates it.

**Comment by rossneilson** [comment]
I also haven't had any issue using the recommended amount with DXD in the new schemes so closing for now

**Comment by daveai** [comment]
This issue reappeared on the following proposal: https://develop.dxvote.dev/#/xdai/proposal/0xa039c58ff367ec23f38546103e3aacd9e135b91d93d56eabdcca3a643974c549

DXvote suggested 240 GEN - which I did and which made the proposal be "stuck". Both Alchemy and DXvote's UI implied sufficient amount was staked, but the proposal only "pre-boosted" after further GEN was staked. So this is likely an issue in the old contracts.
