### ISSUE TITLE
Add final contributor proposal creation page

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#190]
**Partially blocked by #188**

Once the metadata page has been created it can navigate the user to this new page if the proposalType === "Contributor proposal".

This page should have a slider input along the top for selecting contributor compensation level (1-5) .
(Code for this common component can likely be taken from the LinkedButton we already have as it follows a similar structure)

The rewards for each level should be in an easily editable config file and should be scalable for future additional levels that may be added (1-8 etc). 

For now the simple view is enough with automatically populated values for dai, rep and dxd for 1 months work.
Master wallet scheme should be used here in arbitrum and ContributionReward for xdai and mainnet.

DXD ATH should be calculated from coingecko at time of proposal creation. It wont do anything currently but in future will create a vesting contract.

REP can be calculated from current chain distribution but in future will likely lookup across chains.

Additional + button can be left out of this implementation for now (In future it will be used for additional expenses etc)
Simple/Advanced toggle can also be left out.

The screenshots and figma are meant more as wireframes than exact design specifications so some choice lies with the developer on how they should look, feel free to ask for feedback from everyone.
However this screen should be kept as simple as possible.

<img width="910" alt="スクリーンショット 2021-09-28 9 53 53" src="https://user-images.githubusercontent.com/39137239/135055992-529afaa0-f1e4-437c-925a-dfe353d9f454.png">

https://www.figma.com/file/N4e2YuSiv1SycIhmqhIXGB/DXgov?node-id=95%3A2

**Comment by luchux** [comment]
@rossneilson I can take this

**Comment by luchux** [comment]
@rossneilson is someone working in this new proposals components?

**Comment by rossneilson** [comment]
> @rossneilson is someone working in this new proposals components?

Yeah I am, were you also?
I didnt see your comment from before
