### ISSUE TITLE
Prevent reload on network/chain change

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#192]
Currently we fully reload the page on chainChanged in Web3ReactManager.
It seems this is an alright solution that is not uncommon, but if you look at something like swapr switching chains is a lot smoother and faster.

Copying how swapr does this is likely the easiest method to quickly switch chains without reloading the page.

**Comment by fluiddrop** [comment]
Would also be nice to have DXvote prompt you to switch network. I.e. if you click on a link that directs to an xDai proposal, but your wallet is connected to another chain - you will just load the other chain's main DXvote page. Would be nice to get a prompt to switch your wallet to xDai chain - as is quite common in a lot of dApps.
