### ISSUE TITLE
Fix get of undefined IPFS service error

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#198]
Running locally on develop branch there is an issue with ipfs service that tries to get ipfs data before starting the service.

It seems to happen more consistently if you reload a /proposal/id page as it immediately fetches ipfs data.

This should be fixed and also likely adding a try catch would be best.

**Comment by rossneilson** [comment]
@luchux

**Comment by luchux** [comment]
https://github.com/DXgovernance/dxvote/pull/202

**Comment by luchux** [comment]
@rossneilson this is merged, should we close for the moment? 
the PR doesn't fix the issue, just wrap it in a try/catch. We may keep open to investigate to fix the problem itself.

**Comment by rossneilson** [comment]
Nice job fixing the crashing error!

I still think we should fix this, so lets keep it open for now.
Any ideas on how to properly fix it? Maybe just starting service if not already started before accessing it?
Not having the description is not ideal and actually a bit of a security issue and likely something to get a lot questions about.

**Comment by luchux** [comment]
Yeah, I was thinking we could do a sort of retry.

**Comment by luchux** [comment]
The problem is if for any reason the retry keeps failing, should we limit
the amount of retries?

**Comment by rossneilson** [comment]
Yeah, a limit would be a good solution
We could also add a retry button after it fails to let the user manually retry
