### ISSUE TITLE
In advanced call, cannot change "to" value of first call

### ISSUE THREAD

**Issue by luzzif** [DXgovernance/dxvote#201]
**Description**
When trying to create a proposal to send test SWPR on RInkeby to a multisig, I found a bug. I wanted to use advanced calls, and in particular a single call to the test SWPR token with an encoded `transfer` as calldata. Issue is that the first call in the list always had the `to` value set to `0xb05d148c6A9d9C0eb3fE0A091a68d6DeDac63f3b` (which should be the controller). I've tried a couple of things:

- Changing the value manually in the input's element is not working since when clicking "upload to IPFS" the value gets set back to the original one
- Trying to add a new call with the correct `to` value and then delete the old one does not work. Doing so SEEMS to work initially because it lets you set the correct `to` address, but when trying to delete the old one by clicking on the x sign, the new one is deleted instead.

**Comment by hhamud** [comment]
Merged #207
