### ISSUE TITLE
Double counting of GEN/staking token in proposal view

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#210]
**Description**
On the proposal page, there is a double counting of the GEN/staking token. If you look on individual proposals, it's the right amount. I think it's actually only the downstake. It should be 200 GEN, but it shows up as 400 GEN

<img width="261" alt="Screen Shot 2021-10-01 at 5 32 44 PM" src="https://user-images.githubusercontent.com/47428627/135689255-fb3b29e6-b3f5-4c03-ae82-a3b8409f38b9.png">
<img width="390" alt="Screen Shot 2021-10-01 at 5 33 36 PM" src="https://user-images.githubusercontent.com/47428627/135689257-30a13c45-7dc8-4a01-9e52-c55082637b5c.png">

**Comment by luchux** [comment]
@rossneilson I can take this if its still open.

**Comment by rossneilson** [comment]
PR already open #216 ;)
