### ISSUE TITLE
Says "Proposal Rejected" when it's not true

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#211]
**Description**
When you execute a proposal, sometimes it says "Proposal Rejected" when i don't think that's true. It only lasts for a certain amount of time, but not sure what's going on.

It happened on this proposal:
https://dxgovernance.github.io/dxvote/#/xdai/proposal/0x5862d3c65768f03cde19292680aad718b881f46b764c99beba7783eb64baa83a 

<img width="386" alt="Screen Shot 2021-10-03 at 2 33 36 PM" src="https://user-images.githubusercontent.com/47428627/135767349-27e1d907-1daf-4285-84d0-efbcbaa5408b.png">

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Device Information**

- Device: [e.g. PC or mobile phone version]

**Additional context**

**Comment by rossneilson** [comment]
I'm struggling to reproduce this bug, did you do anything beforehand and can you still see it as rejected?

**Comment by luchux** [comment]
can't reproduce either. But I saw this on the past while doing something else. May be a change in the state that is not reloaded? can investigate more if needed

**Comment by powerschris** [comment]
It does not stay like this. It only seems to be for a brief amount of time (a couple minutes), but i have seen it several times.

**Comment by powerschris** [comment]
reproduced this here on this proposal:
https://dxvote.eth.link/#/xdai/proposal/0xefcc7c36f3c4fad2737b1445c4145e3a32a6c6fce8bd5083bbeef2c9e60b1de1 
<img width="710" alt="Screen Shot 2021-10-31 at 7 44 31 PM" src="https://user-images.githubusercontent.com/47428627/139605415-95513863-8de3-40f5-8d32-4017bb3f3df8.png">

It became 'rejected' after I executed it.

The proposal was also not fully executed. The tokens were not sent nor was the REP minted with this execute tx:
https://blockscout.com/xdai/mainnet//tx/0x47b57153ec8541a0b66527b36790e366037dca33271d51347b9179ad51217b1c 

When I did the 'redeem' tx, it did send the tokens and mint the REP. You can see it here:
https://blockscout.com/poa/xdai/tx/0xc0d238fcc38cdd355478fea95f6c2d9118ef46d28794d3e27609934673daf154 

My guess is it says "rejected" when it has been executed but not fully redeemed.

**Comment by powerschris** [comment]
This error is on a bunch of proposals that were just executed in the last day

here's a link to one: https://dxvote.eth.link/#/xdai/proposal/0xab5c26905f6141577c5c37d720b87a36c052ca930497e75212dc476a075dae1f 
<img width="920" alt="Screen Shot 2021-11-22 at 11 21 01 AM" src="https://user-images.githubusercontent.com/47428627/142897403-d89fbd6c-f21c-428e-94dd-13ac09492459.png">

**Comment by rossneilson** [comment]
#368
