### ISSUE TITLE
On Account page, sort by most recent governance activity

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#212]
**Problem Description**
On the Account page there is a "History" section, which is great btw, but now it's sorted where the top is your first governance action, and the bottom is your most recent. this should be reversed. Most recent interactions first. This would be very convenient because I find myself wanting to go to proposals that I've recently interacted with (to boost, vote, execute, etc)

<img width="1216" alt="Screen Shot 2021-10-03 at 2 54 26 PM" src="https://user-images.githubusercontent.com/47428627/135767584-e28e7d90-32b2-4e15-8f98-64fcd0ad24a5.png">

**Comment by rossneilson** [comment]
As an additional feature that may be useful given what you described in the description, maybe a recent activity list in the sidebar of the main proposals page?
<img width="1440" alt="スクリーンショット 2021-10-05 12 10 39" src="https://user-images.githubusercontent.com/39137239/136012546-1356b1da-fa1f-4d8f-8d30-5340477fe0f7.png">

**Comment by powerschris** [comment]
Yeah, definitely. could even have those as three mini sections to separate them more easily.

It also might be cool to see ALL recent governance activity. Like the news feed for governance actions. That's different than the proposals' current state and would likely be it's own tab, but might be a cool/informative view

Have you seen the DeFi firehose on Parsec? https://parsec.finance/features/
<img width="613" alt="Screen Shot 2021-10-05 at 8 54 24 AM" src="https://user-images.githubusercontent.com/47428627/136026595-1fb454ac-2c15-4f10-9a8a-73f24b1a74b3.png">
