### ISSUE TITLE
Gas estimation too high?

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#213]
**Description**
on DXvote.eth.link redeeming/boosting a few proposals on mainnet and DXvote is recommending gas prices that are almost double what I see on Gasnow, ETHgas station and etherscan. Here are two different recommendations for the same action (staking on a proposal) from Alchemy and DXvote. 
From Alchemy:
<img width="318" alt="Screen Shot 2021-10-04 at 9 08 48 AM" src="https://user-images.githubusercontent.com/47428627/135857422-daebdc1f-7401-4f42-b7e5-801e8b903111.png">

From DXvote:
<img width="320" alt="Screen Shot 2021-10-04 at 9 09 06 AM" src="https://user-images.githubusercontent.com/47428627/135857445-acfa7944-afe2-44dc-80db-cc5ee96d19b6.png">

I don't think Alchemy is right either because they aren't using the 'Max priority fee' which is the 1559 stuff. But regardless, it looks like it's consistently estimating almost double the current market price.

**Comment by rossneilson** [comment]
Pretty confident this is not our issue from a dxvote perspective
