### ISSUE TITLE
Automatic filling of SWPR farming campaigns in proposal creation

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#219]
Currently we have the expert mode UI for all proposals. Long term this will be replaced by our new UX flow for various proposal types however as we have a security need for more simplicity doing these proposals frequently and right now this needs a short term fix.

Ideally we want a proposal template that can select default calls in the create proposal screen. Currently these can only set description templates but we should be able to auto populate some calls also.

For swapr farming campaigns this would be the approve call for swpr token and liquidity mining campaign call. 
Any other automation here would be great for security also.

(Longer term solution with new UX flow will also be high priority after this issue is solved to add even more security around these proposals that we often have human error issues with currently)

**Comment by jpkcambridge** [comment]
Can also pre-populate the SWPR staking rewards campaign factory address, which is `0xecA7F78d59D16812948849663b26FE10E320f80C` on Arbitrum, and could also I think default to unlocked and uncapped.
