### ISSUE TITLE
App version/commit on footer

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#225]
**Problem Description**
There is no way to know which version commit is being used in the frontend.

**Desired Solution**
Have a version and short commit in the footer, the version can be taken form the package.json and the short commit can be taken using `git rev-parse --short HEAD` command.

**Proposed Solution**
Edit the `build.sh` script in the script folder to sent those two use those two variables in the build command as REACT_APP_DXVOTE_VERSION and REACT_APP_DXVOTE_COMMIT, if those variables are set show them in the footer, something like: v1.0.1-develop-40aece1db in develop (netlify) v1.0.1-staging-40aece1db in staging (gh-pages), and v1.0.1 (production) in .ens domain

**Comment by luchux** [comment]
PR: https://github.com/DXgovernance/dxvote/pull/273
