### ISSUE TITLE
UI issue in proposals list when filtering

### ISSUE THREAD

**Issue by mprasanjith** [DXgovernance/dxvote#227]
When filtering proposals on the list view, if there aren't many proposals to show the rows get spread out, and looks like this:

![image](https://user-images.githubusercontent.com/25136207/136429408-d508134e-61c2-4afb-9a4f-1fdac480ec68.png)

If there are enough proposals to overflow the default height of the container, this issue does not happen.

**Comment by luchux** [comment]
Im gonna fix this

**Comment by luchux** [comment]
Fixed here: https://github.com/DXgovernance/dxvote/pull/229
