### ISSUE TITLE
Enable right clicking on proposals in the home page list, so you can open a few proposals in new tabs.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#233]
If you sort the list of proposals and then want to open a few in new tabs, you can't. You have to enter each proposal one by one and when you come out of a proposal the sorting is lost. It would be cool to be able to right click on proposals in the list, so you can open them in new tabs and switch between them easily.

**Comment by rossneilson** [comment]
Nice spot and should be a simple fix also, just need to make it an actual link instead of just javascript
