### ISSUE TITLE
Make live vs finished proposals more clear

### ISSUE THREAD

**Issue by 0xVenky** [DXgovernance/dxvote#234]
**Problem Description**
Looking at the proposals home apge, it looks a bit cluttered and takes a while to figure out where the new proposal I created is. Its not sorted based on proposal creation date and it ends in the middle somewhere. Look for ARBIS/WETH or IMX/WETH which are the recently created proposals.

![image](https://user-images.githubusercontent.com/55109759/136709604-5a9ce3a6-4616-43ad-9dc9-451ec507ab54.png)

**Desired Solution**
1. Hide Executed proposals
2. Have different sort options (Sort and filter based on status, sort based on created time)

**Comment by rossneilson** [comment]
Likely a nicer solution would just be to have some spacing between live and finished proposals I think since it is still useful to see previous proposals

**Comment by rossneilson** [comment]
Implement after #298

**Comment by 0xVenky** [comment]
> Likely a nicer solution would just be to have some spacing between live and finished proposals I think since it is still useful to see previous proposals

Sorry, a little late to reply :) Yes, There should be a possibility to see past proposals, but it should not be the first thing to see. Would be great to show by default all active proposals and recently (last 7 days) passed and executed proposals. Just hide away everything else, they all could be displayed when we filter "Executed" proposals.
