### ISSUE TITLE
Tips for certain fields

### ISSUE THREAD

**Issue by 0xVenky** [DXgovernance/dxvote#235]
**Problem Description**
While creating the campaigns, it gets a bit distracting when viewing a lot of numbers and to constantly validate certain things are correct or not.

**Desired Solution**
![image](https://user-images.githubusercontent.com/55109759/136709928-6a14e011-6bc0-49ba-b5e2-f8fc95600ec1.png)

1. The tokens can be in ether terms and not as wei. That is even if a user enters with 18 decimals, a small tip can show that it is equal to 7840 tokens. Makes it so much easier to validate.
2. Time stamp can be translated to UTC time.
3. Even better, timestamp is entered in UTC by some calendar and time utility and it auto converts to UNIX timestamp.
4. Whats the reward token and stakable token, can we fetch from contracts and display IMX-WETH pair or SWPR token?

**Comment by rossneilson** [comment]
Im going to split this up a bit into a few issues. Also much of this will be solved with dedicated UIs for certain proposals

**Comment by rossneilson** [comment]
1. Moved here #250 
2. Moved to #252
3. Moved to #251 
4. This will be fixed in new proposal creation UX flow
