### ISSUE TITLE
Summary after upload to IPFS

### ISSUE THREAD

**Issue by 0xVenky** [DXgovernance/dxvote#236]
**Problem Description**
A summary would be good to see once I upload to IPFS for SWPR farming campaign. It is easier to review and verify. :)

**Desired Solution**
After I fill all the details here and click upload to IPFS, is it possible to show the screen below that?
![image](https://user-images.githubusercontent.com/55109759/136710059-1366a1eb-f9b8-47eb-850a-aec6911911f8.png)

![image](https://user-images.githubusercontent.com/55109759/136710099-e25a9640-556c-4ed6-b074-3f3590a2a1c1.png)

**Alternative Solutions**

**Additional context**

**Comment by rossneilson** [comment]
So the upload to IPFS is actually only uploading the title and description, essentially the metadata, so not much to show. 
In new proposal creation UX flow, this will be clearer and separate. 
Will close for now.
