### ISSUE TITLE
Improve UX around MetaMask connectivity

### ISSUE THREAD

**Issue by mprasanjith** [DXgovernance/dxvote#242]
When connecting MetaMask, the app switches to whatever network MetaMask is connected to and does a refresh. The user most probably want to interact with the page they're on, on the network the app is already connected to instead.

**Comment by rossneilson** [comment]
I think this has been mentioned on a call but I'll write it here also.
The way we likely want to do this is to have the UI connect via the default RPC for the network in the URL if it is different from metamask. We would then need some sort of prompt, likely in the top right asking the user to switch networks. This would also be needed before any transactions could be made.

**Comment by mprasanjith** [comment]
This is almost ready. Will open the PR in a bit.
