### ISSUE TITLE
UI attempting to vote with more REP than user had at proposal creation

### ISSUE THREAD

**Issue by fluiddrop** [DXgovernance/dxvote#243]
DXvote defaults a higher REP amount than I had during proposal creation, which makes the transaction fail: https://blockscout.com/xdai/mainnet/tx/0x5bdad6ca32bf53406a0b10443528ef0837358aa09830f6dcc498c5e8750e566c

The transaction went through fine once I manually reduced the amount of REP to vote with.

**Comment by luchux** [comment]
@fluiddrop @rossneilson you guys still reproduce this?

**Comment by luchux** [comment]
@rossneilson @AugustoL  this is kinda interesting with the new validation, because we can set that max REP based on what the user has. Can we get that info when we load the data in the newProposal, where that data sits?

**Comment by fluiddrop** [comment]
hey @luchux haven't been facing this issue anymore recently - will follow up if it happens again.
