### ISSUE TITLE
Signed Votes

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#25]
The user should be able to sign a vote a share it somehow with the rest of the users. This signed vote can later be executed by anyone in the voting machine.
The signed vote can be signaled, it has to be executed in the voting machine.
One of the possible ways of sharing a signed message across a distributed network is PSS messaging in bee protocol https://docs.ethswarm.org/docs/advanced/pss

**Comment by rossneilson** [comment]
This will become an epic issue once we integrate signed voting in the first guild implementation so closing individual issue for now
