### ISSUE TITLE
Calendar component for inputs

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#251]
NO MORE TIMESTAMPS
Yeah, we can still have a toggle for timestamps but we should also have a calendar popup for inputs.
This will be useful for new UX flow but should be added to custom proposal types also.

**Comment by luchux** [comment]
https://github.com/arqex/react-datetime could be an option here. Very well supported and ranked package.

**Comment by luchux** [comment]
@rossneilson what do you think about that react package. 
And is this something you guys are still working on? (when adding new proposals?) or something that I could work on meanwhile ? I have used this package in the past, and I like it a lot for the simplicity in styling and wrapping the inputs.

**Comment by rossneilson** [comment]
Sorry, I missed this.
Looks good to me, feel free to implement it
