### ISSUE TITLE
Convert all timestamps to UTC time

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#252]
Displaying timestamps in for proposal call param values should be converted to actual times automatically.
The only place we should have timestamps is in advanced views for params etc.

**Comment by luchux** [comment]
@rossneilson at the moment we are using format, as
 `moment
    .unix(proposal.submittedTime.toNumber())
    .format('MMMM Do YYYY, h:mm:ss')
  `
  this is formatted to the user timezone if im not wrong. 
  
  So, whats required is to transform that format into a UTC time?

**Comment by rossneilson** [comment]
> @rossneilson at the moment we are using format, as `moment .unix(proposal.submittedTime.toNumber()) .format('MMMM Do YYYY, h:mm:ss') ` this is formatted to the user timezone if im not wrong.
> 
> So, whats required is to transform that format into a UTC time?

Ny bad, I should have been more specific. This is for the places we still use timestamps like call param values.
Updated the description

**Comment by luchux** [comment]
@rossneilson was checking the proposal calls, but couldn't find any, can you show me an example of one that is showing the timestamp?

**Comment by rossneilson** [comment]
> @rossneilson was checking the proposal calls, but couldn't find any, can you show me an example of one that is showing the timestamp?

Arbitrum would be a good network to check as the swapr campaigns all have timestamps in their calls
