### ISSUE TITLE
Optimize rendering proposals list for better performance

### ISSUE THREAD

**Issue by mprasanjith** [DXgovernance/dxvote#256]
The number of proposals on Xdai already is quite high. When searching or filtering, re-rendering the list already takes a second or two and will continue to get worse as the list grows. While not immediately urgent, its good to have pagination or virtualized components to optimize this.

**Comment by luchux** [comment]
@mprasanjith this is regarding atRep calculation in each rendering. 
The amount of documents is super light to do all the filtering, and the searching. 
can share more insights if you wanna take this. I would wait Sort Filtering to be merged to work on.

**Comment by mprasanjith** [comment]
My assumption was that the performance issues were related to rendering the list. Seems not. Will sort out the IPFS deployments issue, and then come back to this.

**Comment by luchux** [comment]
@mprasanjith ping me when you are on this,  I been trying a lot of things . 
keen to have a chat.

**Comment by luchux** [comment]
opened a PR with an idea, not sure if this should go in develop. Performance flies, but not sure accuracy of the data. 
https://github.com/DXgovernance/dxvote/pull/261
