### ISSUE TITLE
Keep search and filtering when navigating between results.

### ISSUE THREAD

**Issue by mprasanjith** [DXgovernance/dxvote#299]
Search / filtering results get cleared when you open a proposal and then return back to the proposals list. These parameters and search results should be restored when coming back to the proposal list instead. We can even look into [restoring the scroll position](https://reactrouter.com/web/guides/scroll-restoration).

**Comment by luchux** [comment]
Seems our best choice based on the actual patterns in the app, is to use
localStorage.

**Comment by luchux** [comment]
PR opened, with query params
