### ISSUE TITLE
Error if MetaMask is not Connected

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#3]
When trying to connect MetaMask Wallet, get this error if MetaMask has not already been granted permission.

![image](https://user-images.githubusercontent.com/57817726/103971230-d63b2080-511e-11eb-891e-c8b319e8814f.png)

**Comment by AugustoL** [comment]
hmmm, I dont knwo If we can detect taht matamask has not been granted permission, going to try.

Once yo grant permission and refresh it works, right?
