### ISSUE TITLE
DXvote showing double votes for some wallets

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#306]
**Description**
For me, DXvote shows double votes from some wallets.

**Steps to Reproduce**

1. Go to DXvote
2. Find a Proposal with a bunch of votes
3. Scroll down to Voter details
4. See in "History" and "Votes" sections that some wallets show voting twice. Others only once.  

**Screenshots**
![image](https://user-images.githubusercontent.com/57817726/138944114-5d641ff5-7e65-472b-a589-a31f250b2357.png)

**Device Information**

- Browser Brave 
- Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
- Device MacBook Pro

**Additional context**

**Comment by rossneilson** [comment]
Sorry, duplicated in #316 thanks for bug report
