### ISSUE TITLE
Proposals ordering issues

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#307]
It seems proposals are backwards on mainnet under "Execution successful" and so beyond currently active proposals what is shown is the very first proposals in DXdao.
Also currently Expired in Queue is too far up the list. In networks like rinkeby where it happens a lot this is very annoying since new proposals appear very far down the page. Would be great to treat Expired in queue the same as executed.
<img width="1055" alt="スクリーンショット 2021-10-26 21 34 33" src="https://user-images.githubusercontent.com/39137239/138956743-01a47c18-a3bd-42e0-9984-e2f215b4f88d.png">

**Comment by luchux** [comment]
Yeah. Thats a discrepancy in between proposal status and proposal
stateInVotingMachine. Latter is the same but former is different for some
proposals. This is a bug in the generation or assignment of those values.
Will explore and expand more if needed.

**Comment by rossneilson** [comment]
That would explain a lot when I was trying to work out what was going on, thanks Lulli

**Comment by luchux** [comment]
@rossneilson yeah is so ackward haha. But yeah, in this case Expired in Queue, and Queued proposals have the same stateInVotingMachine, but the status field different. So we have a bunch of options to work around this: 
- normalize the attributes on the generation. 
- modify the filtering to use the status as well as the stateInVotingMachine (at least for this case of stateInVotingMachine === 3), and re-order them.

**Comment by rossneilson** [comment]
This issue had two parts:
- Expired in queue
- Incorrect order of finished proposals

Ordering has been solved in #392 

Now this issue is only related to expired in queue being included in In progress proposals when it is not important. 
This is related to complex state logic that needs refactored and so this should be done there

**Comment by hhamud** [comment]
There are additional issues that require further elaboration:
* The following statuses need to be separated from `Executed` in Status settings:
  * Rejected Proposals
  * Passed
