### ISSUE TITLE
Native Token Wrapped ERC20 Support

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#308]
**Description**
We want to move away from native asset transfers and use only ERC20 Transfers and Approvals.

Every network has a Wrapped Token contract, this basically menas that you can lock the native asset, (ETH in mainnet, Xdai in Xdai, etc...) In a Wrapped token contract that uses the deposit and withdraw functions.

The main problem we have and what bring us to this is that the Avatar smart contract that we use to transfer ETH has a default gas cost of 21000 for native assets transfers and after Berlin hardfork we cant send native assets to smart contracts because the gas is higher than 21000 gas, so we need to deploy relayers smart contracts and is a mess.
Besides fixing the transfer of native assets to smart contracts by just using the wrapped ERC20 native assets of each network this will help us to have a unique and standardized way of transferring assets, doing all financial transfers using ERC20.

Wrapped Native Asset functions:
`deposit(uint256)` function signature `0x2e1a7d4d`
This converts the wrapped asset locked to native asset.

`transfer(uint256,address)` function signature `a9059cbb`
This transfers the  locked wrapped asset to other adders, like any ERC20 transfer.

`withdraw(uint256)` function signature `0xb6b55f25`
This converts the wrapped asset locked to native asset.

WETH (Mainnet): https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
Wxdai (xdai): https://blockscout.com/xdai/mainnet/address/0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d
WETH (Arbitrum): https://arbiscan.io/token/0x82af49447d8a07e3bd95bd0d56f35241523fbab1
WETH (Rinkeby): https://rinkeby.etherscan.io/token/0xc778417E063141139Fce010982780140Aa0cD5Ab

**Proposed Solution**
1. Add a `nativeWrapped` key value in each network configuration. 
2. Remove the value input in the basic calls view in WalletScheme
3. Check which walletschemes cant send wrapped native assets.
4. Create proposals to allow the native asset to be transferred in all the schemes that dont have that permission enabled.

**Expected Behavior**
Use wrapped native assets instead of native assets transfers in the wallet scheme calls, this means that if you want to transfer the asset you should do it using an ERC20 wrapped native asset transfer.

**Comment by AugustoL** [comment]
@hhamud you recently worked in the proposal calls, maybe this is good for you.

**Comment by AugustoL** [comment]
We wont have the 21000 gas issue once we use only WalletSchemes, more details and test proving the case here https://github.com/DXgovernance/dxdao-contracts/pull/31

@rossneilson should we do this anyways? I think we dont need it, we can just wait for 1.2 and this issue would be smth from the past.

**Comment by rossneilson** [comment]
> We wont have the 21000 gas issue once we use only WalletSchemes, more details and test proving the case here [DXgovernance/dxdao-contracts#31](https://github.com/DXgovernance/dxdao-contracts/pull/31)
> 
> @rossneilson should we do this anyways? I think we dont need it, we can just wait for 1.2 and this issue would be smth from the past.

Missed this, looks good and certainly would mean we no longer need this.

The short term issue of getting some funds from the avatar not using new architecture into the quick wallet scheme still exists though ...
