### ISSUE TITLE
Warning Dev in navbar

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#311]
**Description**
We need a warning icon in the navbar that has to be showed when the user is using the dapp in any other domain that is not dxvote.eth.link.

**Comment by AugustoL** [comment]
@luchux wanna take this?

**Comment by mprasanjith** [comment]
I think Swapr team added this and then again removed it. I'm not sure if its relevant to us, but I think we should check why they decided to remove it.
