### ISSUE TITLE
REP display component

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#315]
Since REP is a high security part of DXvote it would be nice to have a REP component that we can use when displaying an amount of REP that also shows in brackets that amount as a percentage of current total supply.

It could also take a parameter for `date` that would display "Total supply % as of `date`"

This would be most useful when displaying call data for `mintReputation`

**Comment by luchux** [comment]
@rossneilson could you give us a brief detail of where this is gonna be used? (in which part of the app), to include this as part of the refactor if needed.

**Comment by rossneilson** [comment]
Sure, likely throughout but at first in proposals calls where we show REP being minted

**Comment by rossneilson** [comment]
Implementing #101 here could be useful by showing the exact amount of REP on mouse hover on the percentage value
