### ISSUE TITLE
Cannot submit signal proposal without a Call

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#32]
I'm trying to submit a proposal on the new DXvote on rinkeby. My REP address has been mapped over and i was able to write text into the proposal. I wanted to try and test a 'signal proposal' but when i go to press submit, there is no metamask prompt to confirm the transaction. 

It would be great to have a way to submit a proposal without requesting anything or a call
<img width="1213" alt="Screen Shot 2021-04-08 at 12 26 43 PM" src="https://user-images.githubusercontent.com/47428627/114064359-8e37b100-9867-11eb-8933-81c189b296f7.png">

**Comment by Mi-Lan** [comment]
@powerschris Augusto is going to kill you Chris :D You disregarded rules of issue making xD

**Comment by powerschris** [comment]
I legit looked for the how to submit guide from the call and then couldn't find it. But with the fear of the wrath of @AugustoL, i was able to find the right template.

this one, yeah? https://github.com/AugustoL/dxvote/blob/master/.github/ISSUE_TEMPLATE/feature_request.md 

Or maybe it's this one?
https://github.com/AugustoL/dxvote/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md 


Trying to be better! Does this work? I'm not sure who to assign it to or the labels?

Feature Requestion:
name: Proposal execution without call
about: Submit proposal w/o having to request anything or submit call
title: ''
labels: ''
assignees: ''

**Is your feature request related to a problem? Please describe.** Yes - i couldn't submit a proposal because i didn't know how to fill in the boxes at the bottom.

**Describe the solution you'd like A clear and concise description of what you want to happen.** Signal Proposal submission, requiring no action on DXdao to execute

**Describe alternatives you've considered** I could learn how to enter call data myself but that seems scary.

**Comment by Mi-Lan** [comment]
@powerschris Thats weird i get it automatically once i select issue type.... maybe Augustol will know better

**Comment by AugustoL** [comment]
@powerschris It is fine, I will look to the issue. You should be able to select the type of issue you want to create when you go click in the new issue button, and the template will fill automatically in your issue after you select the type.

**Comment by powerschris** [comment]
This works now! I could "X" out of the calls at the bottom and submitted proposal
