### ISSUE TITLE
On initial loading of the app, Header still request to switch chains

### ISSUE THREAD

**Issue by hhamud** [DXgovernance/dxvote#320]
When loading the application for the first time, the header requests to switch chains when metamask has already been set to the correct chain and is not locked. This header is correctly set upon refreshing the application. 

![image](https://user-images.githubusercontent.com/53880692/139448273-88c7ca91-6e2e-4bd2-b598-2b5abd7f9265.png)

**Comment by rossneilson** [comment]
THere may be some related bugs here,  have frequently seen a white screen appearing when switching as of late
