### ISSUE TITLE
Localhost, GH previews and cloudflare link needs to be whitelisted

### ISSUE THREAD

**Issue by hhamud** [DXgovernance/dxvote#321]
Localhost, GH previews and cloudflare link needs to be whitelisted for the alchemy api to work

**Comment by rossneilson** [comment]
Extra things to whitelist:

- dxvote.dev & develop.dxvote.dev
- Localhost

(We could add PR preview builds but I think the rule would be too general and isn't needed)

Currently I believe only dxvote.eth is whitelisted
