### ISSUE TITLE
Wallet hyperlinks reference incorrect chain

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#323]
If you are on xDai DXvote, say this proposal:
https://dxvote.eth.link/#/xdai/proposal/0xf7fb761631990b9e0ed77b69f6a1f2a9c4da0cf9e76ba0ed52bd2b94e43c2486

And you click on a Wallet/User that has voted or staked on the Proposal, the URL is sending you to the Mainnet User profile, when it should be sending you to the xDai User Profile.

Thanks

**Comment by rossneilson** [comment]
I think this is a different issue where its actually going to the correct chain its just formatting the URL incorrectly
Mainnet is mainnet xdai, somewhat confusing but it should still say xdai chain the top left.
