### ISSUE TITLE
Export as CSV

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#364]
One of my favorite features across the internet is the ability to take the data I'm looking at and export it to CSV format, so it can be analyzed/charted/combined with other things. Coingecko has this feature for their market data, but I think Etherscan does it best. They have a 'Download as CSV' button at the bottom of every page with transaction info, and then allows you to select the dates you want the data. Like so:

<img width="199" alt="Screen Shot 2021-11-09 at 5 39 59 PM" src="https://user-images.githubusercontent.com/47428627/141017305-56f1ff5a-d2c8-497c-883f-50a71c60f442.png">

<img width="781" alt="Screen Shot 2021-11-09 at 5 40 04 PM" src="https://user-images.githubusercontent.com/47428627/141017303-94ab8047-251e-4cb9-92c8-857a92b53434.png">

I think this would be very cool to add to different pages of DXvote. The three that I thought of:
1. Export all proposals as CSV, just a button on the bottom of the proposal view page that would allow you to export over certain time period. Would need to include proposal time/execution, proposer, proposal ID, scheme and any funds transferred or REP minted
2. Finance tab - export the assets in DXdao's treasury into CSV
3. REP holder profile page - would love to export my DXvote transaction history to CSV. When was I most active? How often did I stake. This could actually be very helpful for administrative/tax purposes.

**Alternative Solutions**

**Additional context**

**Comment by rossneilson** [comment]
There are simple libraries for converting json to csv and since we have all the data locally this should be very simple
(I did it manually with an online json->csv converter and console logs to get json objects)
