### ISSUE TITLE
Add holographic consensus reward redemption

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#366]
**User Story**
As a holographic consensus staker, I want to redeem my reward of DXD from the DAO on new scheme types so that we have real holographic consensus and less debt.

**Solutions**
Find out why existing bounty redeem is not working
Test with DXD rewards (and GEN on old schemes)

**Comment by AugustoL** [comment]
im working on this

**Comment by AugustoL** [comment]
fixed in #614

**Comment by skyminelabs** [comment]
Thanks @AugustoL The Redeems for Awards is now showing on my Profile page and I can Redeem.  Thanks!
