### ISSUE TITLE
Add "Passed" status to drop down menu

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#367]
Some proposals go to a "Passed" phase, but this is not accessible in the dropdown menu. Often times this happens when a proposal requires two transactions to fully execute. On multicall proposals, for instance, the proposal needs to be executed and then the multicalls need to be executed. 

It would be nice to see what all the 'passed' ones are so you can sort and find the ones that still need to have the multicall executed
<img width="987" alt="Screen Shot 2021-11-10 at 5 02 18 PM" src="https://user-images.githubusercontent.com/47428627/141201408-373ce5a2-b4f2-418c-8996-1dc49579a76c.png">

**Alternative Solutions**

**Additional context**

**Comment by rossneilson** [comment]
The code around this is a bit messy and we are planning a refactor likely in the next phase of reactors.
So will wait to add it then instead of adding to the existing spaghetti code

**Comment by rossneilson** [comment]
Implemented in #439
