### ISSUE TITLE
Proposal History on Mainnet not showing correctly

### ISSUE THREAD

**Issue by fluiddrop** [DXgovernance/dxvote#372]
If you check the following proposal: https://dxvote.dev/#/mainnet/proposal/0x89638817a4c6ec260bd32b85a2c4363b96e39cfce28f3966f8bb1d136b062250

![image](https://user-images.githubusercontent.com/81422994/141473606-676e78b3-a1e8-45da-b90f-9809ebc083e7.png)

you can see its creation txs under History, but nothing else. However, the proposal is already boosted which means there should at least be 1 staking txs and a StateChange txs.

Creation txs: https://etherscan.io/tx/0xff9984fcdac1386fbc159aafa02bb33f12a79688fe4e55c35ac5dc42ef5af49d
Staking txs: https://etherscan.io/tx/0xc31758c4efbaa44c3a6bbc7f8388bbc19a385f982ad34190ae5709398cd26ff9
StateChange txs: https://etherscan.io/tx/0xd115ca5aae5dd0851c451b97df8ec3f2e8e415661a807189316dcbf2b34684b9

Note that the creation txs went through https://etherscan.io/address/0x08cc7bba91b849156e9c44ded51896b38400f55b while the other two which are not showing went through https://etherscan.io/address/0x332b8c9734b4097de50f302f7d9f273ffdb45b84

**Comment by luchux** [comment]
@rossneilson is this still happening?

**Comment by rossneilson** [comment]
Likely

> @rossneilson is this still happening?

**Comment by rossneilson** [comment]
This seems related to #373 where we have multiple voting machines
