### ISSUE TITLE
Shows "Approve DX" instead of allowing GEN staking

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#373]
**Description**
I was going to boost a proposal through `EnsPublicResolverScheme` that was submitted by Keenan. But in the UI, it doesn't have the option to boost with GEN. Instead it says that I should `Approve DX`
https://dxvote.eth.link/#/mainnet/proposal/0x4be609e3d67ae5da81f8fa62e7cacc7e130b4851a29a45e347ee7432064904bc 

<img width="709" alt="Screen Shot 2021-11-12 at 12 07 54 PM" src="https://user-images.githubusercontent.com/47428627/141506556-044bd526-735f-48ba-b8c5-fb4b5da19e75.png">
On Alchemy, this isn't a problem. I can stake GEN:

﻿﻿https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x4be609e3d67ae5da81f8fa62e7cacc7e130b4851a29a45e347ee7432064904bc 

<img width="842" alt="Screen Shot 2021-11-12 at 12 10 59 PM" src="https://user-images.githubusercontent.com/47428627/141506960-4dea9bab-ed30-4593-9104-5863ec0605d5.png">

**Comment by rossneilson** [comment]
DX!? That's a bizarre one

**Comment by luchux** [comment]
@rossneilson this is still open to work ?

**Comment by rossneilson** [comment]
I fixed it in issue #366 but its not merged

**Comment by rossneilson** [comment]
Seems there is a gen2 voting machine here ?
