### ISSUE TITLE
UI needs to allow users to "6. redeemDaoBounty →"

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#375]
**Description**

xDXdao now has xGEN
https://blockscout.com/xdai/mainnet/address/0xe716EC63C5673B3a4732D22909b38d779fa47c3F/tokens

Need to make the UI show the "6. redeemDaoBounty →" so people can REDEEM

**Comment by rossneilson** [comment]
Duplicate of #366
