### ISSUE TITLE
Treasury page has incorrect token amounts (WETH, wxDai, others)

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#378]
**Description**
On the Info/Finance page on xDai DXvote the token amounts are incorrect. You can see that DXvote says 74 WETH and only 300 WXDAI, but you can see on blockscout, there's actually 33 WETH and 702k WXDai
https://blockscout.com/xdai/mainnet/address/0xe716EC63C5673B3a4732D22909b38d779fa47c3F/tokens 
<img width="1065" alt="Screen Shot 2021-11-15 at 8 51 10 AM" src="https://user-images.githubusercontent.com/47428627/141794662-2f80d695-b333-4732-82c8-87fcad474908.png">

The GEN amount is also wrong. It seems to have problems syncing?

**Comment by hhamud** [comment]
@rossneilson mentioned: 
> Likely this just isnt updated each load time and is only updated on new cache load
As we update cache more often this will be less of an issue
We could also update it locally as we do with proposals etc but very low priority right now
