### ISSUE TITLE
Provide a link to scheme parameters easily accessible from every proposal before and after submission.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#400]
![plugin params](https://user-images.githubusercontent.com/55705611/142449146-a7eb5cc2-2221-4943-b12b-f73a72b9c2bd.PNG)

**Comment by rossneilson** [comment]
I think this is a good power user feature but don't want to be sharing complex scheme details with users for the most part. But this is maybe something we can work with Geronimo to make fit well in the new designs (he has done a great job with power user info so far)
For now you'll need to take a look at the scheme name and refer to the schemes view https://dxvote.dev/#/mainnet/info?view=schemes
