### ISSUE TITLE
Toast notifications and error log modal

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#403]
For example, on Alchemy there is a popup showing: "FAILUREExecute calls: transaction failed :-( - Internal JSON-RPC error. { "code": -32015, "message": "VM execution error.", "data": "Reverted 0x50726f706f73616c2063616c6c206661696c6564" }"

But on DXvote there isn't and one has to get the tx hash and check in the explorer.

**Comment by rossneilson** [comment]
Good call, this is something we could do with toast notifications, something that would be useful generally in DXvote.

This is a good library we used in aqua, look there for an implementation, its quite simple to use.
https://www.npmjs.com/package/react-toastify

We would then, for error notifications, allow users to click them and display a modal popup showing the full error with options to copy the stack trace and instructions to contact the DXgov team or raise an issue.
