### ISSUE TITLE
Proposal state component

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#414]
A component for guilds which shows the state of proposals.

Active = "Ends in x days" 
Finished = "Finished x days ago"

Should take in `endDate` as prop as well as `state` which is optional and used to override "Finished" with "Executed"/"Pending execution"/"Failed"

Add to proposal page under title

<img width="626" alt="Screenshot 2021-11-22 at 13 49 52" src="https://user-images.githubusercontent.com/39137239/142872993-cfa838e4-2b52-47d6-a371-46f255017a9c.png">

Refer to figma for most up to date designs
https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=0%3A1

**Comment by luchux** [comment]
@mprasanjith I did some changes in this component, for good looking in Mobile and Desktop for Guilds/ and also Guilds/proposals.
