### ISSUE TITLE
Boost date time is incorrect?

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#417]
**Description**
(I think) the time a proposal is boosted is not correct in the upper right of the proposal page. I've noticed it on this proposal:
https://dxvote.eth.link/#/xdai/proposal/0x0e5337bd788888a38b397620a831c0cb7e9943db684ca83af1134191224dc7e3 
<img width="345" alt="Screen Shot 2021-11-23 at 1 48 31 PM" src="https://user-images.githubusercontent.com/47428627/143085700-c9c3d586-50d4-43ca-84e1-136d034c9f09.png">

In looking at the proposal, it was submitted with this tx:
https://blockscout.com/xdai/mainnet//tx/0x1f4746ae83d0df6c2774309bd61ec151d3b10c3d50699c9dd8752f767ddb2f73 
And that's displaying correctly in the UI as submitted on Nov 16 at 6:21
The proposal was then staked on with 0.1 DXD with this tx:
https://blockscout.com/xdai/mainnet//tx/0x7a7607cea9359dbfa60aff601006c388dfc6748525ed27ce66a5debd2103996d
This was on Nov 19 at 2:02pm

And then in the UI, it says 'Finish Date' as Nov 22 at 2:02pm. So I'm _guessing_ that the 'Boost Date' in the UI is just 2 days before the 'Finish Date', but it should be 3? 

Or I guess, when exactly is the 'boost time' supposed to be? When a proposal moves from 'pending boost' to 'boosted'?

**Comment by rossneilson** [comment]
We found that this is a bug on the smart contract level which is being addressed. Closing due to no work being needed on FE, only SC and operational work
