### ISSUE TITLE
When switching network, DXvote loads mainnet proposals

### ISSUE THREAD

**Issue by daveai** [DXgovernance/dxvote#431]
When I visit develop.dxvote.dev I wait for the site to load, then switch network to xDai. The website reloads with the spinner and loading proposals from blocks. However, it just re-loads mainnet proposals. To get xDai I have to refresh the site.

**Comment by rossneilson** [comment]
Is this with a wallet connected?

**Comment by rossneilson** [comment]
From @AugustoL investigation

> I think the proposal bug was introduced in this PR, #344 
We already had context defined and we were restarting them, but this detached form the root context just to extend a new type of proposals, IMO this is overkill where a new type could have just been defined and teh methods to filter the proposals would have been able to be added in the daoStore
Now this context is detached from the root context and I think it would have to be restarted separatedly.
I might be wrong, but this was working before without needing hooks and extensions of contexts.
So now we have hooks that are not using the root context and I think this is causing this weird combination of states and context.
Again, I might be wrong, but im pretty sure thats the issue.
