### ISSUE TITLE
User profile shows expired proposals as having "REP redeem"

### ISSUE THREAD

**Issue by daveai** [DXgovernance/dxvote#437]
When going on the user tab Redeems Left shows proposals which are simply expired.

![image](https://user-images.githubusercontent.com/10086922/143900907-835dff8c-d267-463d-be12-69fbfb5d3ef8.png)

However, if you look at the given proposals, they are actually just expired in queue, and therefore there is no REP to be redeemed. 

See: https://develop.dxvote.dev/#/xdai/proposal/0x09bfcd5f90ef175e582f359b86b37078d85d00cf67ac3ea5471d6091c9ff5ca3

**Comment by rossneilson** [comment]
Fixed with use of correct voting machine
