### ISSUE TITLE
Blank Page on DXvote

### ISSUE THREAD

**Issue by daveai** [DXgovernance/dxvote#442]
I have an issue since roughly end of last week ~25/26 Nov 2021, where I simply get a blank screen on DXvote and am unable to load stuff. Even refreshes / clearing cache doesn't seem to help. Towards the end of last week I simply couldn't use DXvote - it would load the given networks homepage, but I was unable to look at single proposals. This week, it seems to happen also when I try to change network.

This behaviour has been observed when:
- Switching networks
- Trying to enter a proposal

What happens:
I simply get a completely white screen

Log files: **[develop.dxvote.dev-1638269284629.log](https://github.com/DXgovernance/dxvote/files/7625115/develop.dxvote.dev-1638269284629.log)**

**Comment by rossneilson** [comment]
Just want to clarify, do you still see this issue?

**Comment by daveai** [comment]
Nope. Not recently.
