### ISSUE TITLE
Pagination in proposals table

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#45]
The proposals table should show a maximum number of proposals per page.

**To Reproduce**
Create a lot of proposals in development and see that there is no pagination.

**Expected behavior**
Show 10 proposals per page.

**To solve and test**
Add lot more of proposals creation and execution in the development script, the more proposals the better, maybe lets have something like +30 different proposals?

**Comment by rossneilson** [comment]
I dont really understand why we want pagination since we dont have the advantages it brings with performance.
#114 Also this was a duplicate and I mentioned why it doesnt make much sense here.
I'll just close it for now since infinite scroll makes sense with all data available on the client
