### ISSUE TITLE
Feature request: One click redemption

### ISSUE THREAD

**Issue by KeenanLukeOM** [DXgovernance/dxvote#459]
Feature request:

Clicking a single button to do all redemptions in a single transaction. If not possible, make the button pop up all redemptions in a sequence.

![image](https://user-images.githubusercontent.com/76129769/144648944-6a17bc71-cec7-4fb0-aa48-163fe0ce27fd.png)

**Comment by rossneilson** [comment]
All redemptions in a single transaction would be something we need to consider from the SC side. 
But the pop up view of all redemptions would make sense and we might implement it during the DXvote redesign, thanks for the suggestion.
