### ISSUE TITLE
Account component

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#468]
This modal should be visible after clocking the account icon in the top right, detailed designs shown below:

Mobile design:
https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=921%3A2384&node-id=1104%3A3356&viewport=499%2C48%2C0.59&scaling=min-zoom&starting-point-node-id=1046%3A2624

Desktop design:
https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=747%3A4460&node-id=747%3A4461&viewport=499%2C48%2C0.23&scaling=min-zoom&starting-point-node-id=747%3A4461&show-proto-sidebar=1

**Comment by rossneilson** [comment]
We can steal from swapr codebase here, will update with links and references soon

**Comment by rossneilson** [comment]
https://github.com/levelkdev/dxswap-dapp/tree/master/src/components/AccountDetails

**Comment by luchux** [comment]
@MiltonTulli for mobile you can have a look at the Filter or the Sidebar GuestActions or MemberActions, we use the DropdownMenu with fullScreenMobile prop as true. 
Ask me whatever you need about it !

**Comment by MiltonTulli** [comment]
This issue has been resolved here https://github.com/DXgovernance/dxvote/pull/485. We should create a new issue to build the mobile part of the modal as it is not included in this pr.
