### ISSUE TITLE
Votes component redesigned

### ISSUE THREAD

**Issue by luchux** [DXgovernance/dxvote#471]
**User Story**
The votes component in proposal display in guilds, has a redesign 

New designs is in https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=254%3A308

**Comment by pimato** [comment]
I hope this will be the final draft design:
![CastVote](https://user-images.githubusercontent.com/5337809/145211356-22664d84-bd4a-4099-a22f-b83bb5a42c35.png)

Changes:
- added tooltip for the Quorum indicater ([Figma design specification](https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=256%3A527):
<img width="950" alt="Bildschirmfoto 2021-12-08 um 13 53 28" src="https://user-images.githubusercontent.com/5337809/145211575-8565aa49-9e2c-4995-b1ae-fe2c0503920e.png">

Figma design specification:
https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=516%3A5190

Figma playground:
https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=0%3A1&node-id=223%3A82&viewport=499%2C48%2C0.19&scaling=min-zoom&starting-point-node-id=124%3A68
