### ISSUE TITLE
Notification indicator in Account Button

### ISSUE THREAD

**Issue by pimato** [DXgovernance/dxvote#472]
Once a user has broadcasted a transaction we should indicate this via a counter icon inside the Account Button:
<img width="858" alt="Bildschirmfoto 2021-12-07 um 18 40 14" src="https://user-images.githubusercontent.com/5337809/145079169-a24d003e-b53a-4c6d-9382-749e67b8c74e.png">

if the transaction got confirmed we should indicate this by not showing the counter anymore.

You can check out the design specification here:
https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=254%3A389

You can play around with the transaction flow which indcludes the transaction counter here:
https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=747%3A4460&node-id=1239%3A4085&viewport=499%2C48%2C0.14&scaling=min-zoom&starting-point-node-id=747%3A4461&show-proto-sidebar=1

**Comment by luchux** [comment]
There is a component called <Badge> that I use in the Filter, you can extend it inside the Button or wherever we use it.
