### ISSUE TITLE
Transaction Modal

### ISSUE THREAD

**Issue by pimato** [DXgovernance/dxvote#473]
Currently DXvote does not provide an insight of a signed transaction. The new modals will allow the user to have more insight about the state of the transaction and allows access to etherscan:
<img width="1600" alt="Bildschirmfoto 2021-12-07 um 18 59 46" src="https://user-images.githubusercontent.com/5337809/145082017-c86ef0d5-689d-4eef-9437-d4b6d6d48e9e.png">

### Waiting for Confirmation:
<img width="541" alt="Bildschirmfoto 2021-12-07 um 19 00 22" src="https://user-images.githubusercontent.com/5337809/145082107-dc2596f0-e461-483e-9662-53541678be5e.png">
This Modal needs to appear before metamask pops up. it indicates to the user that he/she needs to sign the transaction in her/his wallet.

### Transaction Submitted:
<img width="544" alt="Bildschirmfoto 2021-12-07 um 19 01 28" src="https://user-images.githubusercontent.com/5337809/145082291-05dcfc3f-42ac-4eae-b549-31e23b1b3c23.png">
Comes after the user has signed/broadcasted the transaction via wallet/metamask. If a user clicks on View on Explorer he/she will get redirected (with a new tab) to etherscan or blockscout. The user can close the modal with the close icon or the close button.

### Transaction Rejected:
<img width="655" alt="Bildschirmfoto 2021-12-07 um 19 03 52" src="https://user-images.githubusercontent.com/5337809/145082536-98b6e8db-4ada-4308-b10d-5a18e4eed738.png">

Figma design specification:
https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=1239%3A4052

Check out how the modal should work with our playground by joining the guild via staking:
https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=747%3A4460&node-id=747%3A4461&viewport=499%2C48%2C0.09&scaling=min-zoom&starting-point-node-id=747%3A4461&show-proto-sidebar=1

**Comment by luchux** [comment]
@pimato is mobile design link availalbe?

**Comment by pimato** [comment]
yes sir, @luchux 

https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=1239%3A4052
