### ISSUE TITLE
In schemes view the table dissapears after clicking on it.

### ISSUE THREAD

**Issue by dRAT3** [DXgovernance/dxvote#49]
**Describe the bug**
When going to dxvote/#/info?view=schemes the table dissapears when you click on it.

**To Reproduce**
1. Go to https://augustol.github.io/dxvote/#/info?view=schemes
2. Click anywhere in the table
4. Table dissapears

**Expected behavior**
Nothing/Page stays the same

**Screenshots**
![tableinfobug](https://user-images.githubusercontent.com/85542490/121422338-6e0f9580-c96f-11eb-8539-90c0e7b61015.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Brave
 - Version: 1.23.71 Chromium: 90.0.4430.72 (Official Build) unknown (64-bit)

**Additional context**
None

**Comment by AugustoL** [comment]
Should we fixed now, can you confirm @dRAT3 ?

**Comment by dRAT3** [comment]
Yes it's fixed
