### ISSUE TITLE
fix the object spacing

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#496]
The spaces to the left and right are too big and squish the actual content in the middle. It doesn't improve with adjusting the window width, it's fixed.
![DXvote](https://user-images.githubusercontent.com/55705611/146097920-7ce63a63-7f48-42a1-85c7-415164858d4f.png)

**Comment by rossneilson** [comment]
This will all be changed with the redesign so hold tight until then 🙏
