### ISSUE TITLE
Get guild instance data

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#539]
In guilds we currently collect proposal data but we also need to do an initial load of guild data on load 

- getToken()
- getPermissionRegistry()
- getName()
- getProposalTime()
- getTimeForExecution()
- getMaxActiveProposals()

Likely best that we store all this in a context for basic guild instance data

**Comment by rossneilson** [comment]
SWR doesnt leave a lot of work for implementing the data fetching code so we can go straight to implementing this in the UI. 
- getToken, getProposalTime, getTimeForExecution, getMaxActiveProposals- Use in sidebar accessed via "Join" button in left sidebar
- getName - Display in sidebar where "DXdao" currently exists

The others we could perhaps call and just console log to have them technically implemented

**Comment by MiltonTulli** [comment]
Done -  https://github.com/DXgovernance/dxvote/pull/587
