### ISSUE TITLE
When starting New Proposal, we should set some key parameters (most common scenario)

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#54]
**Is your feature request related to a problem? Please describe.**
Not a problem.  But QuickWalletScheme is prob most common use.  It defaults to "RegisterWalletScheme".  Prob not ideal.  Also, I start to create some content, and then realize i didn't have correct Template.  So I change Template, and lose all my content.  

**Describe the solution you'd like**
Set default to most common use.  Also warn people they will lose their content is changing templates.  Or make them choose a template early in the process.  So they can't mess up.  

**Describe alternatives you've considered**
Saving drafts would be cool.  As long as it doesn't get too cluttered.  

**Additional context**
Already informed @AugustoL about this idea

**Comment by AugustoL** [comment]
I set Master Wallet scheme as default for now.

As far as proposal drafts, this would be super cool, but maybe for later?

Right now we are saving the proposal details in the local browser storage, maybe just show a warning when a template is selected? to agree on changing the template and loosing all the content?

**Comment by rossneilson** [comment]
We are working on improved UX flows for specific proposal types, this should fix this problem but since it is solved indirectly by those I'll just close this issue for now
