### ISSUE TITLE
template dropdown filtering

### ISSUE THREAD

**Issue by kermit4** [DXgovernance/dxvote#55]
Template dropdown seems chosen independently of the scheme chosen but I'm guessing they're only appropriate for certain schemes.

**Describe the solution you'd like**
A filtered Template dropdown for the chosen scheme.

**Describe alternatives you've considered**
I could be wrong and maybe all templates are appropriate in all schemes.

**Comment by AugustoL** [comment]
It is fine to show all templates for every scheme for now. Later we can show templates by scheme type, but I dont think it is really needed.
