### ISSUE TITLE
Search by Proposer's address

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#555]
**User Story**
When I want to search for a proposal, sometimes I might not know the name, but the only thing I know about the proposal is who proposed it. It would be great if the search bar could accept addresses of proposal submitters. This is one of the things I still use Alchemy for, because its proposal search has this feature.

It'd _also_ be cool if when you searched by address, you got a link to the address's DXvote page so you could check out all their info.

**Comment by rossneilson** [comment]
Additional cool points for resolving the ens name and searching those addresses too
