### ISSUE TITLE
call function values should strip whitespace after commas

### ISSUE THREAD

**Issue by kermit4** [DXgovernance/dxvote#56]
I seem to have found a pattern where I get "ERROR" (with no description) if the values I enter have spaces after the commans, but otherwise not.

**Describe the solution you'd like**
Strip whitespace around the commas

**Describe alternatives you've considered**
Alternative - require quotes

**Additional context**
I may be wrong as I didn't try too many times.

**Comment by AugustoL** [comment]
Good catch, thx for submitting the bug.
