### ISSUE TITLE
Quiet Ending Period Sorting Incorrectly

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#572]
**Description**
The Atlantic World Proposal needed to be voted down in the last day because of an incorrect address. This means the proposal went into the "Quiet Ending Period" because a proposal needs to stay either FOR or AGAINST for 2 days. This changes the state on genesis protocol and on DXvote its labeled as "Quient Ending Period"

Currently, proposals in this state show up below the Expired Proposals, when in reality they should be near the top, or in the chronological order of when the proposal will be finished.

<img width="958" alt="Screen Shot 2022-01-14 at 3 49 54 PM" src="https://user-images.githubusercontent.com/47428627/149583375-8fcf233f-2195-4cbb-b1bc-244e1bd4a517.png">

At the minimum, it should be moved up ahead of all other states except for boosted (In queue, pre-boosted, pending boost)

**Comment by powerschris** [comment]
It seems like this issue is still here. Here's a list of proposals on the multicall scheme. In my view the first proposal should be the one that is set to pass the soonest. Here, it's all of the regular proposals first _and then_ the quiet ending proposal. 

I don't think there is a reason to separate quiet ending period and regular proposals in their sorting. I get they are different states in the voting machine but they should be sorted by when the proposal _ends_

<img width="1047" alt="Screen Shot 2022-03-01 at 1 59 12 PM" src="https://user-images.githubusercontent.com/47428627/156231972-fb72f86e-7a39-41eb-a81c-b0c1e737557f.png">

**Comment by powerschris** [comment]
Same thing. The Quiet Ending Period proposal appears at the bottom instead of at the top 

<img width="907" alt="Screen Shot 2022-03-29 at 1 08 15 PM" src="https://user-images.githubusercontent.com/47428627/160667397-726547a8-ccf8-437e-99ac-5b34a1e92487.png">

**Comment by hhamud** [comment]
Do you want the QuietEndingPeriod state to be equal to the Boosted state in ranking order?

**Comment by powerschris** [comment]
Yes, there are two ways it could be sorted:
1. In the same ranking order as Boosted, and its rank within the Boosted state would be determined by how long until it will pass
2. Above the boosted state, because "Quiet Ending Proposals" deserver more attention because they are may be contentious

My preference is #1
