### ISSUE TITLE
Voting with less than full amount of REP shows an incorrect recap

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#574]
**Description**
Voting with less than full amount of REP shows an incorrect recap

**Steps to Reproduce**

On Dxvote xDai, if i vote with full REP amount, I see a correct "State after your vote" percentage.
![image](https://user-images.githubusercontent.com/57817726/149687174-e5f47481-ac0a-4691-9389-5925ed6584d7.png)

If I alter the amount of REP I want to vote with, I see:
![image](https://user-images.githubusercontent.com/57817726/149687264-26c6decd-b3e5-4ae9-b311-387ceb593dbb.png)

The new "percentage" doesn't make sense.  

The voting seemed to work... mostly
![image](https://user-images.githubusercontent.com/57817726/149687416-7ab60470-1b03-4199-a233-519d502ae1c1.png)

I voted with 1.5%, not 1.49%.  It's showing 1.49%

Thanks

**Comment by hhamud** [comment]
State vote calculation in the modal is depreciated in upcoming version, however the truncating of values can be fixed.
