### ISSUE TITLE
Failed ContributionReward proposal not showing failed

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#579]
We had to vote down an incorrect boosted proposal, this worked but has highlighted some bugs since we rarely fail proposals like this. 
Currently, the proposal is failed yet shows passed dispute the obvious majority voting against. 
Hopefully this is just a simple bug relating to ContributionReward but the solution should check it works for all sorts of proposals.
The redeem button also appears which it should not, once status shows properly this should disappear. 

https://develop.dxvote.dev/#/xdai/proposal/0xbd4c0dca243d6e2b73bd79e27b12b75a8253bfdf8d44584ac738c304d881ec7e

**Comment by MiltonTulli** [comment]
@rossneilson 
After debugging I noticed on `dxvote/src/utils/proposals.ts L112` this switch case: 
```js
    case VotingMachineProposalState.Executed:
      if (
        proposal.stateInScheme === WalletSchemeProposalState.Rejected &&
        schemeType === 'ContributionReward'
      )
        return {
          status: 'Passed', 
  ```
I don't think this is an issue, maybe [this](https://develop.dxvote.dev/#/xdai/proposal/0xbd4c0dca243d6e2b73bd79e27b12b75a8253bfdf8d44584ac738c304d881ec7e) is an edge case and we need to add a new switch case. If that is correct, I need first to understand when a proposal is actually 'rejected' and why if `proposal.stateInScheme` is rejected but is `ContributionReward` type that is considered a success case.
