### ISSUE TITLE
Execution succeeded on a proposal that had no votes, only stakes.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#58]
Execution succeeded of a proposal that had no votes, only stakes.
https://augustol.github.io/dxvote/#/proposal/0x86b2ff51fb5afca4caa5b42cd448ae0d1acd70d5d32f877a6170ad5eda4129f3
![success](https://user-images.githubusercontent.com/55705611/123875193-16b97100-d8ee-11eb-851d-6480e462a1b2.PNG)

**Comment by AugustoL** [comment]
Yes, the execution should show failed. Let you know when I fix it.
