### ISSUE TITLE
Proposal Description Spilliing out of Proposal Box

### ISSUE THREAD

**Issue by hhamud** [DXgovernance/dxvote#581]
> I'm seeing some strange behaviour in mobile view that isn't present in develop. I also think the modal is being rendered underneath in the next screen in mobile
> 
> <img alt="Screenshot 2022-01-17 at 10 20 03" width="503" src="https://user-images.githubusercontent.com/39137239/149751655-e06cd6de-8537-4dac-869d-57e81ebe8f02.png">

This weird behaviour happens also in develop, 
![image](https://user-images.githubusercontent.com/53880692/149786113-fa0951a8-5552-498c-b968-369e1a28a6d1.png)

It's because of the description proposal text not wrapping around within the box, so this causes all the modals to break.

Regarding the second issue of the modal appearing behind the lock dxd modal, madusha had pointed it out [here](https://github.com/DXgovernance/dxvote/pull/511#issuecomment-1014326531) and the same reason applies here as well, I chose to create the modal there only for reviewing purposes.

Once this PR goes through, then the next stage can go ahead and I can remove the modal from triggering at that spot and ensure that the modal only appears after closing the lock dxd modal notification.

_Originally posted by @hhamud in https://github.com/DXgovernance/dxvote/issues/511#issuecomment-1014598151_

**Comment by mprasanjith** [comment]
@hhamud I'm not sure if this helps fix this issue, but we decided to not have the proposal description in the proposal cards (at least for now). Wanted to make sure you don't put extra effort if its already fixed.

**Comment by hhamud** [comment]
Could you tell me which branch the change has taken affect in? @mprasanjith so that I can then close this issue

**Comment by mprasanjith** [comment]
> Could you tell me which branch the change has taken affect in? @mprasanjith so that I can then close this issue

Its included in https://github.com/DXgovernance/dxvote/pull/617.

**Comment by hhamud** [comment]
No longer an issue as #617 removes description from proposal card
