### ISSUE TITLE
Clicking link in Proposal should open a new tab

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#585]
I was reading about walletscheme update in this proposal:
https://develop.dxvote.dev/#/xdai/proposal/0xe6689b68c699b8296a654af19ca9c14c470e2fc158f5fa610d611a6c85513362

And then wanted to do what the proposal said and visit the blockscout link to verify, but it opened in my current tab instead of opening a new one. 

It seems to me it would be better to open in new one because a user probably wants to maintain their place in the proposal.

**Comment by rossneilson** [comment]
Maybe possible to change a config for this? Wont be an issue once we move away from this editor
<img width="309" alt="Screenshot 2022-01-24 at 15 51 22" src="https://user-images.githubusercontent.com/39137239/150816648-384feba9-6194-4a37-90e8-2715467835b0.png">
