### ISSUE TITLE
Rep is not consistent across history and voting

### ISSUE THREAD

**Issue by hhamud** [DXgovernance/dxvote#586]
Rep is not consistent across history and voting, e.g.
![image](https://user-images.githubusercontent.com/53880692/149995856-9eab73ce-e973-4bfc-8fc2-af619315e55e.png)

![image](https://user-images.githubusercontent.com/53880692/149995903-1a662e5a-ee6b-4aa9-b078-38672b0c5c39.png)

**Comment by hhamud** [comment]
History component uses total rep rather than total rep at the time of proposal creation.

**Comment by MiltonTulli** [comment]
Just to clarify, the idea is to fix proposal history events to fetch totalREPSupply at a specific block/time (`proposal.creationEvent.blockNumber`) as [vote section is doing](https://github.com/MiltonTulli/dxvote/blob/8ea14c74b5f5991c0a974697099c58c60dcdb3ca/src/components/Proposal/Votes/index.tsx#L186)
