### ISSUE TITLE
'back to proposals' button takes you back to the main page, but the newly submitted proposal isn't listed until f5

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#59]
After submitting a proposal, the button 'submit proposal' changes to 'back to proposal', which takes you to the main page with the list of proposals, but the proposal one has just submitted is not visible in the list until one refreshes the page.

**Comment by AugustoL** [comment]
Yes, a known bug, will fix it tomorrow.

**Comment by rossneilson** [comment]
I think we have the data for this available in the UI side already just need to show it on update

**Comment by rossneilson** [comment]
Involve in refactor of proposals page

**Comment by rossneilson** [comment]
@AugustoL This may be a good issue to address in the ongoing cache refactors
