### ISSUE TITLE
Switching networks doesn't load new network proposals with Frame

### ISSUE THREAD

**Issue by daveai** [DXgovernance/dxvote#593]
When switching network through the DXvote UI, it triggers the user wallet (Metamask / Frame) to change network. Confirming the change of network changes the DXvote url - but doesn't actually load the proposals of that network - it stays on the original network.

![image](https://user-images.githubusercontent.com/10086922/150325898-6632ac6b-e0bd-4767-97f0-d2d968626bc8.png)

**Comment by hhamud** [comment]
is this also happening on develop.dxvote.eth?

**Comment by daveai** [comment]
yes - I actually went to .eth.link to check if it was happening there too. But I mostly only use develop and it always happens.

**Comment by rossneilson** [comment]
Worth maybe @mprasanjith taking a look at this and its PR also since he has so far handled the networks in dxvote

**Comment by rossneilson** [comment]
Could this just be frame @daveai ?

**Comment by hhamud** [comment]
Note: from @mprasanjith, "The latest version of Frame seems to actually crash DXvote if I switch network through the wallet."

**Comment by daveai** [comment]
Can we turn this into a support Frame on DXvote feature request? :)
