### ISSUE TITLE
Updated sidebar when user is member

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#594]
We have a slight revision to the design of the lefthand sidebar 
Main change is the new infromation button and the new position for the member display. 
The voting power for the user is also displayed in the bottom user button.

Issue will be updated later with what the information button should open

<img width="234" alt="Screenshot 2022-01-20 at 11 51 39" src="https://user-images.githubusercontent.com/39137239/150333654-644571df-0859-4841-8d2b-fec92d873770.png">

https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=2914%3A17643

**Comment by MiltonTulli** [comment]
@rossneilson current dropdown action should be removed here?

**Comment by rossneilson** [comment]
Lets keep it for now
And for the information button for now we can just toggle the staking modal
