### ISSUE TITLE
rep voting isn't accurately reflected in proposals

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#60]
Created a new proposal and instead of using 0.27%, I only voted Yes with 0.05%
In different places the yes vote shows either as 0.00%, 0.27% or Infinity, but not 0.05%.
https://augustol.github.io/dxvote/#/proposal/0x8b218da7092303fdbdbbf43312b27701f4a1cd9e19170da70956010e5c92f60f
https://augustol.github.io/dxvote/#/user/0xD97672177E0673227FA102C91BFA8b8cfA825141
![3](https://user-images.githubusercontent.com/55705611/123877458-102cf880-d8f2-11eb-9f66-26a39030fedd.PNG)
![4](https://user-images.githubusercontent.com/55705611/123877489-1e7b1480-d8f2-11eb-9d25-51bbd0db892d.PNG)

**Comment by AugustoL** [comment]
Check it again now, let me know if you find it weird somewhere else.

**Comment by sacshin** [comment]
Looks awesome now, brujo!
