### ISSUE TITLE
In the same session /without logging out/, clicking on 'new proposal' shows the content of the last proposal /of the same user/.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#61]
This isn't necessarily a bug.
If one has created or started creating a proposal and closed it, then clicking on 'new proposal' shows the content of the old one as a custom template.
One can just delete the text and write a new one, or if one didn't finish submitting the old one, one can just continue writing it and submit it, which is very convenient.

**Comment by AugustoL** [comment]
That the goal, to save the last state of the proposal. For now is only saving the title and description, but it shoudl save the scheme selected, and calls too.
