### ISSUE TITLE
It is possible to create a proposal with no title.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#62]
It is not possible to create a proposal without a description, which is great, but it is possible to create a proposal without a title, which shouldn't be allowed.
The newly created prposal was given a title automatically 
https://augustol.github.io/dxvote/#/proposal/0x6d1d0f0e4917373d69578892a5fbe5096b1a48262202d56c939f10c03dcb5612
![5](https://user-images.githubusercontent.com/55705611/123880969-977d6a80-d8f8-11eb-8e45-337130d5a8ae.PNG)
![6](https://user-images.githubusercontent.com/55705611/123881015-ab28d100-d8f8-11eb-82fb-a2c2878812d3.PNG)

**Comment by AugustoL** [comment]
fixed in https://github.com/AugustoL/dxvote/pull/52/commits/32e560959d0f8e09d982428acc1fdd5fc4cb3fb4
