### ISSUE TITLE
Add Proposal type to URL

### ISSUE THREAD

**Issue by hhamud** [DXgovernance/dxvote#624]
Could we make this add the actual proposal type to the URL?

_Originally posted by @rossneilson in https://github.com/DXgovernance/dxvote/pull/597#discussion_r794572179_

* needs proposal type templates to be completed beforehand.

**Comment by AugustoL** [comment]
This is meant to be used in the "new proposal" page?

**Comment by rossneilson** [comment]
> This is meant to be used in the "new proposal" page?

Yeah, we should really avoid making issues that are just references to comments.
This is just to add the proposal type to the link to the next create proposal page, a one line change
