### ISSUE TITLE
Add sorting logic functionality to the proposal list

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#63]
Allow the list of proposals on the main page to be sorted https://augustol.github.io/dxvote/#/ , e.g. by the time remaining.
Also the numbering is weird. I created a proposal and it was number 3, then I created a second one and it is number 2, not 4.
![7](https://user-images.githubusercontent.com/55705611/123881456-9a2c8f80-d8f9-11eb-842a-50a8e97d8740.PNG)

**Comment by AugustoL** [comment]
So order the proposals by the time that it has left to be finished instead of the order of creation?

**Comment by sacshin** [comment]
It wouldn't necessarily need to be so by default, but it would be nice to have it as an option.
