### ISSUE TITLE
Dealing with the QWS in DXvote.eth

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#634]
**Description**

Dealing with the QWS in DXvote.eth is causing some confusion

**Steps to Reproduce**

https://dxvote.eth.link/#/xdai/proposal/0x808f00f6005b541e539c8033cb57c2c4c9528ee8865f9895f65a9c23a9bd00b8
This proposal is messed up.
The QWS has no money.  Is the QWS also broken?

Is there anyway to get the staked DXD back.
John tried to down stake it, but a bug wouldn't let him.

![image](https://user-images.githubusercontent.com/57817726/152090081-21a623de-9eb4-4cb9-8d12-78d8b4a2bd7e.png)

maybe The UI needs some better info communicated.  When choosing the "Contributor" button, it's not clear it's using a QWS.

It's also not clear you need to check the QWS to see if it has money.
and how to do this.
I think the UI would need to tell you all this.

**Comment by rossneilson** [comment]
Ok, lets split this up a little:
This issue can continue to be for the error occurring when downstaking a proposal.
I'll make another issue for a feature request to have a preview or check that the scheme in use has funds available. As for the user knowing what scheme its using, we eventually would want this in advanced settings somewhere but generally we don't want users selecting schemes in the new UX.
