### ISSUE TITLE
Investigate crash when using the ERC20 contract JSON with Ether-SWR

### ISSUE THREAD

**Issue by mprasanjith** [DXgovernance/dxvote#647]
Ether-SWR seems to crash when using the ERC20 contract JSON file we have in src/contracts/ERC20.json. I had to add another ABI to src/abis/ERC20.json for now. We need to investigate this.

**Comment by AugustoL** [comment]
Im using balanceOf and approval from ERC20 in https://github.com/DXgovernance/dxvote/pull/602, works good.
