### ISSUE TITLE
Guild Styling

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#658]
We now have styling with more of a dark mode for most components in figma and since we are using themes for our CSS in guilds it should be relatively simple to change.
@pimato should look over the preview deploy to ensure everything has been covered to catch up with the figma.

**Comment by 0xvangrim** [comment]
https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3332%3A15324

https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=3332%3A15606&node-id=3555%3A11926&viewport=388%2C48%2C0.22&scaling=scale-down&starting-point-node-id=3332%3A15607&show-proto-sidebar=1
