### ISSUE TITLE
DXvote on xDai showing sending the native token as ETH instead of xDai

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#66]
**Describe the bug**
DXvote on xDai showing sending the native token as ETH instead of xDai

**To Reproduce**
1. Go to https://augustol.github.io/dxvote/#/proposal/0x4dce5ec32697c8cb405f347d32c7581066af9997eefc2a73f37d0c98d734ac1f  (on xDai Chain)
2. Look at proposal
3. Scroll down to "Calls"
4. See it showing ETH 

**Expected behavior**
Expect to see "xDai"

**Screenshots**
![image](https://user-images.githubusercontent.com/57817726/126040104-00f707e7-5456-4953-9ddd-f9bf072d6572.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave

**Comment by AugustoL** [comment]
Should be fixed now, commit https://github.com/AugustoL/dxvote/pull/52/commits/e759618f45752387584512ebc4a15f86c4dbdc1e
