### ISSUE TITLE
Enable disconnecting one's address from the DXvote dApp.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#663]
Allow users to disconnect their addresses from DXvote.

**Comment by rossneilson** [comment]
I think generally this is handled by the wallet, no?

**Comment by sacshin** [comment]
Alchemy had it. We're also adding it to Swapr as it's good UX, other DEXes have it already. It's nothing urgent, but it won't hurt to have it in DXvote, it could be useful for the Guilds.

**Comment by rossneilson** [comment]
Fair enough, can get @pimato to add it to the designs

**Comment by pimato** [comment]
@rossneilson will work on it.

**Comment by pimato** [comment]
Hey guys, I´ve added a Disconnect flow to our connection process. Therefor, we need to add a disconnect button to the Network Modal. You can play around with the connect/disconnect process [here](https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=3332%3A15606&node-id=3332%3A17779&viewport=325%2C48%2C0.23&scaling=min-zoom&starting-point-node-id=4453%3A16717)! The Network Modal will have two states, Disconnected and Connected:

### Connected
<img width="396" alt="Change" src="https://user-images.githubusercontent.com/5337809/156773197-e5f1bf57-c0ff-4594-b2a2-875e74cde56e.png">

[Figma design specification](https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3918%3A19836)

- Reachable via the account modal by clicking on change can be played around with [here](https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3332%3A17779)!
-If the user clicks on the `Disconnect - Button` the modal closes and we change the header to:
<img width="1440" alt="disconnected" src="https://user-images.githubusercontent.com/5337809/156773582-481e181f-9db5-4e30-9c06-f15d01963601.png">

- If the user clicks on `Connect Wallet - Button` we will show him the network modal in the disconnected state:
<img width="396" alt="Connect" src="https://user-images.githubusercontent.com/5337809/156773960-389a9e71-b5c5-4d33-9917-771ae54eae51.png">

[Figma design specification](https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=4812%3A17122)
