### ISSUE TITLE
Would like an easy way to see the Proposals I have already voted on on front page

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#67]
**Is your feature request related to a problem? Please describe.**
Would like an easy way to see the Proposals I have already voted on on front page

**Describe the solution you'd like**
A little thumbs up or mark on front view letting me know I have already voted on that proposal. (Similar to Alchemy)

**Describe alternatives you've considered**
Open to other better ideas.

**Additional context**
Image: I can't see what i have already done.

![image](https://user-images.githubusercontent.com/57817726/126040279-5453b5eb-acde-4eea-8c8b-c296806cfa26.png)

**Comment by AugustoL** [comment]
Added icons in created, voted, and staked proposals in proposals page.
