### ISSUE TITLE
Guilds portal page

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#678]
We need a page where multiple guilds can be displayed for the user to select. This is the page they would land on by going to guilds.eth.link

Designs are ready and should be simple.
<img width="850" alt="Screenshot 2022-02-28 at 12 32 36" src="https://user-images.githubusercontent.com/39137239/156054399-a85d64b4-b7bc-456f-a627-1069e349e4fb.png">

The current plan for how we index these is going to be using ens subdomains. This is the trickier part of the issue.
There are a few ways we could find subdomains of an ens address. The first would be on the smart contracts but as far as I can tell they don't keep track of subdomains on the contract however it is worth exploring more. 
We could make a cache like in dxvote but this is slow and has too much overhead for something simple like this.
The other option is the subgraph, something we have stayed away from for governance. Since in this case there is no reliance on this data, it is just a nice overview page it should be fine even if the subgraph is unreliable. 
https://thegraph.com/hosted-service/subgraph/ensdomains/ens

You can refer to dxdao as an ens with a subdomain to test and the test guild we have deployed should also be hardcoded in.

Additional steps would then be to check each found subdomain for the required metadata values and to check if the contract is deployed, and on what networks, before displaying it as an option.

**Comment by AugustoL** [comment]
Hola, the best way to index public important information would be using a smart contract, lets write an upgradeable smart contract owned by dxdao avatar where we can add/remove official guilds.

The contract needs to be upgradeable so later we can create guilds from there, use it as a guild factory and index.

So it would as simple as fetch a public array of the guild addresses and then for each guild fecth the public data from their contracts, such as name and total members.

**Comment by rossneilson** [comment]
Implementation decided on is the smart contract register approach creating a dependence here on 
https://github.com/DXgovernance/dxdao-contracts/issues/86
