### ISSUE TITLE
DXvote will not open on Chrome Browser for me

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#68]
**Describe the bug**
DXvote will not open on Chrome Browser for me

**To Reproduce**
1. Go to https://augustol.github.io/dxvote/#/
Getting White screen

**Expected behavior**
Expect DXvote to load.

**Screenshots**
![image](https://user-images.githubusercontent.com/57817726/126055947-103deaac-1e94-42ff-9346-ee00b4ef8295.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 91.0.4472.114 (Official Build) (x86_64)

**Additional context**

**Comment by AugustoL** [comment]
I had the same issue and I didnt had metamask installed, that was why. Fixed in https://github.com/AugustoL/dxvote/pull/52/commits/f327e985b0898df6287852649a6e50bbdd26432c
