### ISSUE TITLE
user does not change when changed in MetaMask

### ISSUE THREAD

**Issue by kermit4** [DXgovernance/dxvote#70]
**Describe the bug**
At https://augustol.github.io/dxvote/#/ the address show and the address the person icon links to seems stuck at one of my addresses.

**To Reproduce**
Change account in Metamask
reload
address in links are previous account, even after reloading page

**Expected behavior**
Address should update to new account when reloading page.

**Desktop (please complete the following information):**
Brave  1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)

**Comment by AugustoL** [comment]
@kermit4 should be fixed now, please check.

**Comment by kermit4** [comment]
It is fixed.
