### ISSUE TITLE
Update locking modal to new styles

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#704]
Our current implementation has chanegd slightly from the figma. The text seems a lot darker and the input seems old and not dark themed. 

<img width="532" alt="Screenshot 2022-03-18 at 11 37 46" src="https://user-images.githubusercontent.com/39137239/158996495-29342c09-c977-4737-ab5b-a97a0069c555.png">

<img width="398" alt="Screenshot 2022-03-18 at 11 36 18" src="https://user-images.githubusercontent.com/39137239/158996293-db6f11a9-82a7-4e11-8eec-167669378a75.png">

**Comment by mprasanjith** [comment]
This issue is also present in other modals as well, its better to fix all of them in one go.
