### ISSUE TITLE
Allow users to remove actions from the actions widget

### ISSUE THREAD

**Issue by pimato** [DXgovernance/dxvote#706]
Currently, the transaction builder is only able to add actions and edit actions but not remove actions from the `Actions - Widget`. We need to add a button to allow actions to be removed. You can play around with the playground [HERE](https://www.figma.com/proto/cjLng0AbOKuDj9r5oZVDmR/Wireframe?page-id=4442%3A17030&node-id=4442%3A17031&viewport=325%2C48%2C0.1&scaling=min-zoom&starting-point-node-id=4442%3A17031) .

### Action Widget with removable Action
<img width="699" alt="Desktop" src="https://user-images.githubusercontent.com/5337809/159008925-63358df2-2375-4171-b254-d3996c1f5c37.png">

### Confirmation Modal
![RemoveAction](https://user-images.githubusercontent.com/5337809/159009086-f28e1457-343d-4bca-b6b4-cf7face0894b.png)
- Once the user clicks on the `Remove - Button` from the action component in the `Actions - Widget` we need an additional user confirmation.
- User can cancel the removal or `confirm removal` which will remove the action from the `Actions - Widget`
- [Figma design specification](https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=5350%3A18055)

**Comment by carlbarrdahl** [comment]
I built something similar two months ago and I remember putting some work into the state management for the form to handle nested actions like this. I used React Hook Form.

Maybe it can help out:
![screenshot](https://github.com/carlbarrdahl/near-voting/raw/master/screenshot.create.png)
https://github.com/carlbarrdahl/near-voting

Relevant code:
https://github.com/carlbarrdahl/near-voting/blob/master/src/components/ProposalForm.js#L54
