### ISSUE TITLE
Redeems Left shows amounts not yet redeemabble

### ISSUE THREAD

**Issue by kermit4** [DXgovernance/dxvote#71]
**Describe the bug**
https://augustol.github.io/dxvote/#/user/0x7FB1D2CF886A66f0A2D6a4c841f529F116E274B1 shows https://alchemy.daostack.io/dao/0xe716ec63c5673b3a4732d22909b38d779fa47c3f/proposal/0x40056c6e14da53484ebb29cacabb466caf7eadf222d8334e051eec42ac7c340e as redeemable but it has not ended.

**To Reproduce**
Open above links

**Expected behavior**
Redeems left should show only what is redeemable now.

**Desktop (please complete the following information):**
Brave  1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)

**Comment by AugustoL** [comment]
Thx! I will add the condition check in the code to show only finished proposals redeemable

**Comment by AugustoL** [comment]
Fixed in https://github.com/AugustoL/dxvote/pull/52/commits/b98581ff541487260e0cba91942e200cbed9d045
