### ISSUE TITLE
Develop shows "Tx will fail" but DXvote.eth does not

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#711]
**Description**
I was going to boost this proposal:
https://develop.dxvote.dev/#/xdai/proposal/0xea97c70d686535ad265bfee1396e629e85edb5d585055a60b8655cc37e542e22 
 but on Develop i got this warning label
<img width="361" alt="Screen Shot 2022-03-21 at 7 44 42 PM" src="https://user-images.githubusercontent.com/47428627/159381680-641fd117-15cf-42ae-a10c-5e020d726eba.png">
This was the raw transaction data:
0x2daedd52ea97c70d686535ad265bfee1396e629e85edb5d585055a60b8655cc37e542e2200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000 

I went to the same proposal on Dxvote.eth.link and there wasn't any error message when I boosted the proposal:

https://dxvote.eth.link/#/xdai/proposal/0xea97c70d686535ad265bfee1396e629e85edb5d585055a60b8655cc37e542e22

**Comment by rossneilson** [comment]
Apologies I think I missed this bug report, have you seen his again in either environment?
