### ISSUE TITLE
Add minting to transfer and mint component

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#726]
Fully shown in the figma this functionality should only be enabled on rep guild implementations

**Comment by 0xvangrim** [comment]
https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=5502%3A18946

**Comment by rossneilson** [comment]
We can conditionally render this based on `isRepGuild` from useGuildImplementation hook
