### ISSUE TITLE
_small_ issue with dropdown menu

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#73]
**Describe the bug**
When you select 'custom' in the drop down menu, you can't go back to the other options. Super super small and I only created an issue because i was able to record a nice video for it!
I was able to 'x' out of the custom call and then click 'add call' to get the original drop down menu 
**Desktop (please complete the following information):**
 - OS: mac os 11.4
 - Browser Chrome
 - Version 92

https://user-images.githubusercontent.com/47428627/127047835-657170cc-5aa1-4881-a713-7de5043315a6.mov

**Comment by AugustoL** [comment]
@powerschris thats how it is supposed to work, if you select custom you go to the "advanced" call, where you enter the address and teh encoded data, if you click in the "simple" button it should take you back to the simple call edition. Can you confirm it works when you click simple?

**Comment by powerschris** [comment]
yes! i think that works
