### ISSUE TITLE
App crashes when the tx to execute the proposal gets confirmed

### ISSUE THREAD

**Issue by luzzif** [DXgovernance/dxvote#74]
**Describe the bug**
As the title says, as soon as the tx to execute the tx gets confirmed, a white screen of death appears.

**To Reproduce**
1. Go to a passed proposal awaiting for execution
2. Click on "execute"
3. Wait for the resulting tx to get confirmed
4. A WSOD should now appear

**Expected behavior**
I'd expect the proposal's state to update accordingly after the execution succeeded.

**Screenshots**
![image](https://user-images.githubusercontent.com/12766550/127635516-9c7b9d1f-77e1-47b5-9577-09131a65d08c.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Brave
 - Version: 1.15.76 Chromium: 86.0.4240.111

**Comment by AugustoL** [comment]
Should be fixed now.
