### ISSUE TITLE
Action Builder: Handle undecodable calls gracefully

### ISSUE THREAD

**Issue by mprasanjith** [DXgovernance/dxvote#749]
In the proposal actions viewer, the UI should fall back to showing raw call data (`from` / `to` / `data` / `value`) if we fail to decode the proposal calls using the contract registry.

**Comment by rossneilson** [comment]
This is the worst case scenario for proposal actions where we cant find rich contract data.
After this we have an issue for the medium case where we find sourcify ABI #755
