### ISSUE TITLE
One Proposal in DXvote won't load

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#75]
**Describe the bug**

I redeemed almost all my proposals.

However:
https://augustol.github.io/dxvote/#/proposal/0xe5458d37fa43303502dda80de884f83ec23898225e645a482ea8519e9693744a
I have this one on my list that won't load.  And I can't see it in alchemy either

it's here:
![image](https://user-images.githubusercontent.com/57817726/127892784-a1d8f27a-3a96-4e2b-8aaa-66ade3161c4d.png)

**To Reproduce**
1. Go to https://augustol.github.io/dxvote/#/user/0x1861974f32eaCDCceD0F81b0f8eCcFeD58153a9D
2. Click on Proposal
3. Won't load

**Expected behavior**
Expect it to load.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave

**Additional context**

**Comment by AugustoL** [comment]
@skyminert please check in 10 min, should be fixed now.

Fixed on this commit. https://github.com/AugustoL/dxvote/pull/52/commits/2a8e69a3f0c6857357a69682d090b5fe4b368e11

**Comment by skyminelabs** [comment]
Now, I can not even go to the URL:
https://augustol.github.io/dxvote/#/user/0x1861974f32eaCDCceD0F81b0f8eCcFeD58153a9D

It forwards to: https://augustol.github.io/dxvote/#/xdai/proposals
