### ISSUE TITLE
"Redeem Beneficiary" button shows on executed proposal page

### ISSUE THREAD

**Issue by adamazad** [DXgovernance/dxvote#77]
**Describe the bug**

When viewing executed proposals, the _Redeem Beneficiary_ button shows. Submitting the redeem transaction does not cause a revert (by design maybe?). I assumed it would revert, making the UX even worse.

**To Reproduce**
1. Go to [Proposal #0x8bed672b86b68a06e487cb1139c6b4e27303f0eb36daffce389c0c4aa33b76d5](https://augustol.github.io/dxvote/#/xdai/proposal/0x8bed672b86b68a06e487cb1139c6b4e27303f0eb36daffce389c0c4aa33b76d5)
2. _Redeem Beneficiary_ button shows.

**Expected behavior**

_Redeem Beneficiary_ button should not show on executed proposals.

**Screenshots**

![image](https://user-images.githubusercontent.com/1926216/128930038-1d998a39-6993-4c92-95e5-69ad356a7aa6.png)

**Comment by AugustoL** [comment]
@adamazad should be fixed now.

**Comment by adamazad** [comment]
Closing for now
