### ISSUE TITLE
Duration input component

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#806]
We have a date time picker right now where we work out the number of seconds until that time but we also need a duration input for better UX in specific cases. For example with vesting contracts we specify time until cliff, this makes sense to sue this component. However with the existing date time that would make sense for choosing specific end dates for inputs. 

We want a component styled the same as the time input of current react-datetime but with number inputs horizontally for:
Years | Months | Days | Hours | Minutes | Seconds
This should return the time in seconds

**Comment by hhamud** [comment]
is there a figma for this available?
