### ISSUE TITLE
On-chain polling with scalar range voting.

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#82]
At this point, this will be a feature for DXgoV2, rather than DXvote.
Currently with DAOstack voting is just categorical and only binary - yes/no. 
It would be useful, in DXgoV2, to allow REP/DXD holders to vote on, if not proposals then at least signal votes, which represent at least multiple choice categorical markets, but ideally also scalar markets if needed. For example, a signal vote for staking Eth or stablecoins for treasury diversification could be a market $0 - $15m, and voters can vote 0 if they don't want it at all, or use a slider to choose any amount to signal how much they believe is appropriate.

**Comment by rossneilson** [comment]
This is addressed actually in guilds as we have a feature which is essentially a competition scheme and will likely come to dxvote in a future wallet scheme version update
