### ISSUE TITLE
Boosted Proposals not showing

### ISSUE THREAD

**Issue by powerschris** [DXgovernance/dxvote#836]
**Description**
When loading current proposals on Gnosis Chain on develop, all of the boosted proposals are not showing up
<img width="1601" alt="Screen Shot 2022-05-05 at 3 54 28 PM" src="https://user-images.githubusercontent.com/47428627/167015093-1701fb9a-2136-489f-8e22-7ce4fe1f67a9.png">

This does not ocurr on .eth.limo where the proposals load fine:

<img width="1512" alt="Screen Shot 2022-05-05 at 3 52 44 PM" src="https://user-images.githubusercontent.com/47428627/167015110-a5002a30-6e56-4c1a-9ffb-bb5ef593adb5.png">

**Comment by rossneilson** [comment]
I am seeing them load for me but lets investigate @AugustoL I think there are cache changes not in production yet so looks like a new bug
