### ISSUE TITLE
Set permissions core function call

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/dxvote#843]
We need an additional core action in the guild proposal actions builder. We currently have good examples for transfer and mint functions so this should follow the same pattern. We need a "Set Permissions" call. This allows our guilds to set their own specific permissions to control what is allowed and not allowed.
There is a lot we could do for this but for now, we will keep it simple. 

This is a call we do to the guild contract itself `setPermission(address[] memory asset,
        address[] to,
        bytes4[] functionSignature,
        uint256[] valueAllowed,
        bool[] allowance)`

We will show two main types of permissions to be set in the UI for now:
- Asset transfers
- Function calls

For asset calls we want an input for token and token amount (we already have these components in the UI). These will then encode as `asset` and `valueAllowed`. We should also add a button to set the token amount to max value (MAX_UINT). 
We also need a "To Address" input that is optional if left blank it will be ANY_ADDRESS. 
The remaining `functionSignature` should be set to`ANY_SIGNATURE`. 
We will also need to add special encoding conditions for transferring the native network token as this works differently. 

For function calls we want inputs for "To Address" and "Function signature". We will then need to hash the function signature to bytes4. I need to investigate more to find what exactly the other parameters should be set to for this permission type. 

ANY_ADDRESS = address(0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa)
ANY_SIGNATURE = bytes4(0xaaaaaaaa)

We also need to display this when we show decoded proposal data (creating the proposal is encoding and we need to decode when showing existing proposal actions). We can just follow the same logic as transfer functions here and the code structure is set up to allow additional types. In future we will show more here but for now we can just display a simple bit of text describing the permissions being set.

**Comment by dcrescimbeni** [comment]
The basic functionality is finished, but there are pending things to decide:
1. What should the token address be set when setting function calls?
2. How to show the decoded proposal data. Currently, it only shows "Permission -> 0xaddress"
3. I'm working on saving and displaying the function name when setting the permissions to make a function call



![Image](https://user-images.githubusercontent.com/75996796/169152353-04c77192-02a8-466f-8186-e16a50ce2928.png)
![Image](https://user-images.githubusercontent.com/75996796/169152352-f5655ec8-0d21-46db-a7f0-7b1d2dc58693.png)
