### ISSUE TITLE
Problem with Redeem - User is not Redeeming the share of xDXdao's staked xGEN

### ISSUE THREAD

**Issue by skyminelabs** [DXgovernance/dxvote#85]
**Describe the bug**
When you Redeem on DXvote, user only gets back the xGEN stake the user staked.  The user does not get the share of reward that xDXdao has staked (200 xGEN)

**To Reproduce**
1. Go to a proposal that you staked on
2.  Once finished, Redeem
3. You should get back your stake plus share of 200 xGEN
4. You only get back your stake

**Comment by AugustoL** [comment]
@skyminert let me knwo if it is fixed.
