### ISSUE TITLE
cross-chain governance

### ISSUE THREAD

**Issue by sacshin** [DXgovernance/dxvote#86]
Nico may have a solution for cross-chain governance
We should think of a way for contributors to submit a proposal on any chain and be able to choose on which networks to take effect when it passes, so it can be executed on any of the dao's chains without the need to conduct the vote on a specific one.
This can save time, and also save gas fees on eth mainnet.
The simplest example would be contributor compensation. A proposal can be on xdai, and the contributor can select to be paid on xdai, but get rep on all chians /eth mainnet, xdai, arbitrum/. If having two actions make it too complicated, the contributor can separate the rep request from the stablecoin compensation.

**Comment by hhamud** [comment]
That's an interesting idea. Did Nico supply you with any more information?

**Comment by rossneilson** [comment]
Just to clarify, this is a super complex issue to do in a decentralised way and something that if we want to go after we would need to put serious research resources into. Likely not a realistic item to prioritise at this time.

Unless someone has had a shower thought on how it could be done.

Maybe best to close and reopen if we have more technical thoughts on how this could be done.

**Comment by hhamud** [comment]
> Just to clarify, this is a super complex issue to do in a decentralised way and something that if we want to go after we would need to put serious research resources into. Likely not a realistic item to prioritise at this time.
> 
> Unless someone has had a shower thought on how it could be done.
> 
> Maybe best to close and reopen if we have more technical thoughts on how this could be done.

Features like these will blow out the competition and should be thought of as we go along.

**Comment by rossneilson** [comment]
> Features like these will blow out the competition and should be thought of as we go along.

Very true, however we also need to consider scope. This is a challlenge that entire teams of very smart people are dedicated to and there is a reason no decentralised solution exists yet. 
It's a little like building a rocket to get to a planet and at the same time researching teleportation.
