### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by AugustoL** [DXgovernance/dxvote#87]
Add dark mode to be enabled/disabled with an icon in the navbar.

The click on the icon should change the darkMode value in the config store.

The theme/index.ts file should change the dapp styles based on the value of the darkMode in the config store.

**Comment by adamazad** [comment]
Assigning myself @AugustoL.

**Comment by AugustoL** [comment]
We dont know how the styles in dark mode are going to be, I gfuess it would be enough to just change the background and a few colors for now, making sure we are loading the right styles depending on the light/dark mode used.

**Comment by rossneilson** [comment]
Do we have any update on this? I think it would make more sense to leave this until after we have the redesign to decide if we even need a dark mode. A better, simpler option could just be to have the new design be darker
