### ISSUE TITLE
IPFS titles not resolving on homepage

### ISSUE THREAD

**Issue by daveai** [DXgovernance/dxvote#917]
Over the past few days IPFS has not been resolving consistently in DXvote

![image](https://user-images.githubusercontent.com/10086922/178288062-73093bb5-61fa-4573-b7f7-41f32a1c0966.png)

We had a similar issue a few months ago. However, it seems slightly different now. As back in the days when you clicked on the proposal the IPFS would still not resolve. But if I click on any of the proposal where the title hasn't loaded now on the DXvote homepage, it loads immediately once you're in the actual proposal.

Not sure if we've done any changes recently around IPFS title resolving? Or perhaps it's just IPFS acting up.

**Comment by rossneilson** [comment]
Related to #912 we removed constant spam to fetch ipfs titles but in turn some proposals which were not added to proposal title list in cache are not being fetched
