### ISSUE TITLE
Redeems left section is missing the proposals created by connected wallet

### ISSUE THREAD

**Issue by adamazad** [DXgovernance/dxvote#94]
**Describe the bug**

I can see the proposals created by others, but not my own. on Alchemy, I can see the Redeem button when viewing my proposals.

Example on Alchemy from a proposal I can redeem REP from because I created it.

![image](https://user-images.githubusercontent.com/1926216/131227818-3d8f68fd-28ef-4b64-8e29-85f0ea6024d8.png)

But this doesn't show on DXvote

**Comment by AugustoL** [comment]
@adamazad con you check if it is happening now?
