### ISSUE TITLE
Fix OS combability issues in `yarn build`

### ISSUE THREAD

**Issue by adamazad** [DXgovernance/dxvote#98]
Comparing paths using `/` doesn't work when trying to build the production build in:

https://github.com/AugustoL/dxvote/blob/508f376e18d0ba66f35991182d2c385ddac97e54/config-overrides.js#L31-L40

Using `path.join` fixes this.

**Comment by rossneilson** [comment]
Yarn build seems to work fine now and have had no issues from other developers so closing for now. Re-open if still an issue.
