### ISSUE TITLE
Repo setup for developer experience DX

### ISSUE THREAD

**Issue by adamazad** [DXgovernance/dxvote#99]
It's almost straightforward to start contributing to the repo. I like to improve the DX for future contributors:

### Update Node engine to v14 LTS

Most devs use v14 LTS, but the `develop` branch is strictly requiring v12 of the engine.

### `.editorconfig`

Unifies the codebase styling

```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false
```

### `.prettierrc`

Works along with `.editorconfig`
```
{
  "arrowParens": "avoid",
  "semi": false,
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true,
  "printWidth": 120,
  "trailingComma": "es5"
}
```

### Scripts in `package.json`

For linting and formatting the code if the IDE can't pick up Prettier

```json
"scripts": {
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "lint": "eslint src/ --ext .js,.ts,.tsx",
}
```

**Comment by AugustoL** [comment]
@adamazad yes! And add a CI script for the linter to be executed on PRs to any branch but master and develop.

One PR to update to nodev14, (remember to also update the CI workflows)

Another PR to submitting the linter and script config and CI workflows.

**Comment by adamazad** [comment]
The repo setup is missing unit tests. We can add them once #117 and #118 are merged

**Comment by rossneilson** [comment]
This looks closed to me
